Platinum UPnP SDK: PLT_HttpListenTask Class Reference
PLT_HttpListenTask Class Reference
The PLT_HttpListenTask class is used by a PLT_HttpServer to listen for incoming connections and spawn a new task for handling each request.
#include <PltHttpServerTask.h>
Protected Member Functions
virtual void DoAbort ()
This method to override in derived classes is called when the task is about to stop.
virtual void DoRun ()
This method to override in derived classes is the main task loop.
Detailed Description
The PLT_HttpListenTask class is used by a PLT_HttpServer to listen for incoming connections and spawn a new task for handling each request.
Member Function Documentation
virtual void PLT_HttpListenTask::DoAbort () [inline, protected, virtual]
This method to override in derived classes is called when the task is about to stop.
Reimplemented from PLT_ThreadTask.
virtual void PLT_HttpListenTask::DoRun () [inline, protected, virtual]
This method to override in derived classes is the main task loop.
Reimplemented from PLT_ThreadTask.
References PLT_ThreadTask::IsAborting(), PLT_ThreadTask::Kill(), and PLT_TaskManager::StartTask().
The documentation for this class was generated from the following file:
PltHttpServerTask.h