Platinum UPnP SDK: PLT_DeviceHost Class Reference
PLT_DeviceHost Class Reference
UPnP Device Host.
#include <PltDeviceHost.h>
Public Member Functions
PLT_DeviceHost (const char *description_path="/", const char *uuid="", const char *device_type="", const char *friendly_name="", bool show_ip=false, NPT_UInt16 port=0, bool port_rebind=false)
Creates a new instance of UPnP Device Host.
virtual NPT_UInt16 GetPort ()
Returns the port used by the internal HTTP server for all incoming requests.
virtual void SetBroadcast (bool broadcast)
When enabled, the device will use the interface broadcast address to announce instead of the UPnP Multicast address 239.255.255.250.
virtual void SetByeByeFirst (bool bye_bye_first)
When a UPnP device comes up, the specifications require that a SSDP bye-bye sequence is sent to force the removal of the device in case it wasn't sent properly during the last shutdown.
Protected Member Functions
virtual NPT_Result AddIcon (const PLT_DeviceIcon &icon, const void *data, NPT_Size size, bool copy=true)
Add UPnP icon information to serve using static image.
virtual NPT_Result AddIcon (const PLT_DeviceIcon &icon, const char *fileroot, const char *urlroot="/")
Add UPnP icon information to serve from file system.
NPT_Result Announce (NPT_HttpRequest &request, NPT_UdpSocket &socket, bool byebye)
Called during SSDP announce.
virtual NPT_Result OnAction (PLT_ActionReference &action, const PLT_HttpRequestContext &context)
This mehod is called when an action performed by a control point has been received and needs to be answered.
virtual NPT_Result OnSsdpPacket (const NPT_HttpRequest &request, const NPT_HttpRequestContext &context)
PLT_SsdpPacketListener method called when a M-SEARCH SSDP packet is received.
virtual NPT_Result ProcessGetDescription (NPT_HttpRequest &request, const NPT_HttpRequestContext &context, NPT_HttpResponse &response)
This method is called when a control point is requesting the device description.
virtual NPT_Result ProcessHttpGetRequest (NPT_HttpRequest &request, const NPT_HttpRequestContext &context, NPT_HttpResponse &response)
This method is called when a "GET" request for a resource other than the device description, SCPD, or icons has been received.
virtual NPT_Result ProcessHttpPostRequest (NPT_HttpRequest &request, const NPT_HttpRequestContext &context, NPT_HttpResponse &response)
This method is called when a "POST" request has been received.
virtual NPT_Result ProcessHttpSubscriberRequest (NPT_HttpRequest &request, const NPT_HttpRequestContext &context, NPT_HttpResponse &response)
This method is called when a request from a subscriber has been received.
virtual NPT_Result SendSsdpSearchResponse (NPT_HttpResponse &response, NPT_UdpSocket &socket, const char *st, const NPT_SocketAddress *addr=NULL)
Called by PLT_SsdpDeviceSearchResponseTask when responding to a M-SEARCH SSDP request.
virtual NPT_Result SetupDevice ()
Default implementation for setting up device host.
virtual NPT_Result SetupIcons ()
Default implementation for registering device icon resources.
virtual NPT_Result SetupResponse (NPT_HttpRequest &request, const NPT_HttpRequestContext &context, NPT_HttpResponse &response)
NPT_HttpRequestHandler method for setting up the response of an incoming HTTP request.
virtual NPT_Result SetupServices ()=0
Required method for setting up UPnP services of device host (and any embedded).
virtual NPT_Result SetupServiceSCPDHandler (PLT_Service *service)
This method is called when the device starts to register the SCPD url handler with SCPD document for each service.
virtual NPT_Result Start (PLT_SsdpListenTask *task)
Called by PLT_TaskManager when the device is started.
virtual NPT_Result Stop (PLT_SsdpListenTask *task)
Called by PLT_TaskManager when the device is stoped.
Static Protected Member Functions
static NPT_Result Announce (PLT_DeviceData *device, NPT_HttpRequest &request, NPT_UdpSocket &socket, bool byebye)
Static method similar to Announce.
static NPT_Result SendSsdpSearchResponse (PLT_DeviceData *device, NPT_HttpResponse &response, NPT_UdpSocket &socket, const char *st, const NPT_SocketAddress *addr=NULL)
Static method similar to SendSsdpSearchResponse.
Friends
class PLT_Service
class PLT_SsdpAnnounceInterfaceIterator
class PLT_SsdpDeviceSearchResponseInterfaceIterator
class PLT_SsdpDeviceSearchResponseTask
class PLT_UPnP
Detailed Description
UPnP Device Host.
The PLT_DeviceHost class is a base class for implementing a UPnP Device. It handles network announcements and responses to searches from ControlPoints. ControlPoint action invocations are also received and delegated to derived classes. A PLT_DeviceHost also takes care of eventing when services state variables change.
Constructor & Destructor Documentation
PLT_DeviceHost::PLT_DeviceHost (const char * description_path = "/", const char * uuid = "", const char * device_type = "", const char * friendly_name = "", bool show_ip = false, NPT_UInt16 port = 0, bool port_rebind = false)
Creates a new instance of UPnP Device Host.
Parameters:
description_path Relative path for description url
uuid UPnP device unique id
device_type UPnP device type
friendly_name Name advertised for UPnP device
show_ip Flag to indicate if device IP should be appended to friendly name
port local port for the device host internal HTTP server, 0 for randomly selected.
port_rebind Flag to indicate if device host should automatically try to look for another port if failing to choose the one passed.
Member Function Documentation
virtual NPT_Result PLT_DeviceHost::AddIcon (const PLT_DeviceIcon & icon, const void * data, NPT_Size size, bool copy = true) [protected, virtual]
Add UPnP icon information to serve using static image.
Parameters:
icon the icon information including url path
data the image data
size the image data size
copy boolean to indicate the data should be copied internally
virtual NPT_Result PLT_DeviceHost::AddIcon (const PLT_DeviceIcon & icon, const char * fileroot, const char * urlroot = "/") [protected, virtual]
Add UPnP icon information to serve from file system.
Parameters:
icon the icon information including url path
fileroot the file system root path
urlroot the url root path of the icon url to match to fileroot Note: As an exemple, if the icon url path is "/images/icon1.jpg", the fileroot is "/Users/joe/www" and the urlroot is "/", when a request is made for "/images/icon1.jpg", the file is expected to be found at "/Users/joe/www/images/icon1.jpg". If the urlroot were "/images", the file would be expected to be found at "/Users/joe/www/icon1.jpg".
NPT_Result PLT_DeviceHost::Announce (NPT_HttpRequest & request, NPT_UdpSocket & socket, bool byebye) [inline, protected]
Called during SSDP announce.
The HTTP request is already configured with the right method and host.
Parameters:
request the SSDP pre formatted request
socket the network socket to use to send the request
byebye boolean indicating if the announce is a SSDP bye-bye or alive.
References Announce().
static NPT_Result PLT_DeviceHost::Announce (PLT_DeviceData * device, NPT_HttpRequest & request, NPT_UdpSocket & socket, bool byebye) [static, protected]
Static method similar to Announce.
Parameters:
device the device to announce
request the SSDP pre formatted request
socket the network socket to use to send the request
byebye boolean indicating if the announce is a SSDP bye-bye or alive.
Referenced by Announce().
virtual NPT_UInt16 PLT_DeviceHost::GetPort () [inline, virtual]
Returns the port used by the internal HTTP server for all incoming requests.
Returns:
port
virtual NPT_Result PLT_DeviceHost::OnAction (PLT_ActionReference & action, const PLT_HttpRequestContext & context) [protected, virtual]
This mehod is called when an action performed by a control point has been received and needs to be answered.
Parameters:
action the action information to answer
context the context information including the HTTP request and local and remote socket information (IP & port).
Reimplemented in PLT_MediaServer.
virtual NPT_Result PLT_DeviceHost::OnSsdpPacket (const NPT_HttpRequest & request, const NPT_HttpRequestContext & context) [protected, virtual]
PLT_SsdpPacketListener method called when a M-SEARCH SSDP packet is received.
Parameters:
request SSDP packet
context the context of the request
Implements PLT_SsdpPacketListener.
virtual NPT_Result PLT_DeviceHost::ProcessGetDescription (NPT_HttpRequest & request, const NPT_HttpRequestContext & context, NPT_HttpResponse & response) [protected, virtual]
This method is called when a control point is requesting the device description.
Parameters:
request the HTTP request
context the context information including local and remote socket information.
response the response to setup.
Reimplemented in PLT_MediaServer.
virtual NPT_Result PLT_DeviceHost::ProcessHttpGetRequest (NPT_HttpRequest & request, const NPT_HttpRequestContext & context, NPT_HttpResponse & response) [protected, virtual]
This method is called when a "GET" request for a resource other than the device description, SCPD, or icons has been received.
Parameters:
request the HTTP request
context the context information including local and remote socket information.
response the response to setup.
Reimplemented in PLT_MediaServer.
virtual NPT_Result PLT_DeviceHost::ProcessHttpPostRequest (NPT_HttpRequest & request, const NPT_HttpRequestContext & context, NPT_HttpResponse & response) [protected, virtual]
This method is called when a "POST" request has been received.
This is usually an UPnP service action invocation. This will deserialize the request and call the OnAction method.
Parameters:
request the HTTP request
context the context information including local and remote socket information.
response the response to setup.
virtual NPT_Result PLT_DeviceHost::ProcessHttpSubscriberRequest (NPT_HttpRequest & request, const NPT_HttpRequestContext & context, NPT_HttpResponse & response) [protected, virtual]
This method is called when a request from a subscriber has been received.
This is for any new subscritions, existing subscrition renewal or cancellation.
Parameters:
request the HTTP request
context the context information including local and remote socket information.
response the response to setup.
virtual NPT_Result PLT_DeviceHost::SendSsdpSearchResponse (NPT_HttpResponse & response, NPT_UdpSocket & socket, const char * st, const NPT_SocketAddress * addr = NULL) [inline, protected, virtual]
Called by PLT_SsdpDeviceSearchResponseTask when responding to a M-SEARCH SSDP request.
Parameters:
response the SSDP pre formatted response
socket the network socket to use to send the request
st the original request search target
addr the remote address to send the response back to in case the socket is not already connected.
References SendSsdpSearchResponse().
static NPT_Result PLT_DeviceHost::SendSsdpSearchResponse (PLT_DeviceData * device, NPT_HttpResponse & response, NPT_UdpSocket & socket, const char * st, const NPT_SocketAddress * addr = NULL) [static, protected]
Static method similar to SendSsdpSearchResponse.
Parameters:
device the device to announce
response the SSDP pre formatted response
socket the network socket to use to send the request
st the original request search target
addr the remote address to send the response back to in case the socket is not already connected.
Referenced by SendSsdpSearchResponse().
virtual void PLT_DeviceHost::SetBroadcast (bool broadcast) [inline, virtual]
When enabled, the device will use the interface broadcast address to announce instead of the UPnP Multicast address 239.255.255.250.
Parameters:
broadcast boolean to indicate the use of broadcast address
virtual void PLT_DeviceHost::SetByeByeFirst (bool bye_bye_first) [inline, virtual]
When a UPnP device comes up, the specifications require that a SSDP bye-bye sequence is sent to force the removal of the device in case it wasn't sent properly during the last shutdown.
Parameters:
bye_bye_first Boolean to indicate that SSDP bye-bye sequence should be sent first or not.
virtual NPT_Result PLT_DeviceHost::SetupDevice () [protected, virtual]
Default implementation for setting up device host.
This calls SetupServices and SetupIcons when device starts.
virtual NPT_Result PLT_DeviceHost::SetupIcons () [protected, virtual]
Default implementation for registering device icon resources.
Override to use different ones. Called when device starts.
virtual NPT_Result PLT_DeviceHost::SetupResponse (NPT_HttpRequest & request, const NPT_HttpRequestContext & context, NPT_HttpResponse & response) [protected, virtual]
NPT_HttpRequestHandler method for setting up the response of an incoming HTTP request.
Parameters:
request the request received
context the context of the request
response the response to set up
virtual NPT_Result PLT_DeviceHost::SetupServices () [protected, pure virtual]
Required method for setting up UPnP services of device host (and any embedded).
Called when device starts.
Implemented in PLT_MediaServer.
virtual NPT_Result PLT_DeviceHost::SetupServiceSCPDHandler (PLT_Service * service) [protected, virtual]
This method is called when the device starts to register the SCPD url handler with SCPD document for each service.
virtual NPT_Result PLT_DeviceHost::Start (PLT_SsdpListenTask * task) [protected, virtual]
Called by PLT_TaskManager when the device is started.
Parameters:
task the SSDP listening task to attach to for receiving SSDP M-SEARCH messages.
virtual NPT_Result PLT_DeviceHost::Stop (PLT_SsdpListenTask * task) [protected, virtual]
Called by PLT_TaskManager when the device is stoped.
Parameters:
task the SSDP listening task to detach from to stop receiving SSDP M-SEARCH messages.
The documentation for this class was generated from the following file:
PltDeviceHost.h