/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myandroid_paintboard_ImageProc */

#ifndef _Included_com_myandroid_paintboard_ImageProc
#define _Included_com_myandroid_paintboard_ImageProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myandroid_paintboard_ImageProc
 * Method:    imgproc
 * Signature: (Landroid/graphics/Bitmap;IIILandroid/graphics/Bitmap;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_myandroid_paintboard_ImageProc_imgproc
  (JNIEnv *, jclass, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
