; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	E:\GitHub\codesandnotes\xy-vsfilter\src\subtitles\SSF.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	?Reload@CRenderer@ssf@@UAGJXZ			; ssf::CRenderer::Reload
PUBLIC	?SetStream@CRenderer@ssf@@UAGJH@Z		; ssf::CRenderer::SetStream
PUBLIC	?GetStream@CRenderer@ssf@@UAGHXZ		; ssf::CRenderer::GetStream
PUBLIC	?GetStreamInfo@CRenderer@ssf@@UAGJHPAPA_WPAK@Z	; ssf::CRenderer::GetStreamInfo
PUBLIC	?GetStreamCount@CRenderer@ssf@@UAGHXZ		; ssf::CRenderer::GetStreamCount
PUBLIC	?GetClassID@CRenderer@ssf@@UAGJPAU_GUID@@@Z	; ssf::CRenderer::GetClassID
PUBLIC	??_R4CRenderer@ssf@@6B@				; ssf::CRenderer::`RTTI Complete Object Locator'
PUBLIC	?Render@CRenderer@ssf@@UAGJAAUSubPicDesc@@_JNAAUtagRECT@@@Z ; ssf::CRenderer::Render
PUBLIC	?IsAnimated@CRenderer@ssf@@UAG_NPAU__POSITION@@@Z ; ssf::CRenderer::IsAnimated
PUBLIC	?GetStop@CRenderer@ssf@@UAG_JPAU__POSITION@@N@Z	; ssf::CRenderer::GetStop
PUBLIC	?GetStart@CRenderer@ssf@@UAG_JPAU__POSITION@@N@Z ; ssf::CRenderer::GetStart
PUBLIC	?GetNext@CRenderer@ssf@@UAGPAU__POSITION@@PAU3@@Z ; ssf::CRenderer::GetNext
PUBLIC	?GetStartPosition@CRenderer@ssf@@UAGPAU__POSITION@@_JN@Z ; ssf::CRenderer::GetStartPosition
PUBLIC	??_R4CRenderer@ssf@@6BISubPicProviderEx@@@	; ssf::CRenderer::`RTTI Complete Object Locator'
PUBLIC	?NonDelegatingQueryInterface@CRenderer@ssf@@UAGJABU_GUID@@PAPAX@Z ; ssf::CRenderer::NonDelegatingQueryInterface
PUBLIC	??_R4CRenderer@ssf@@6BCUnknown@@@		; ssf::CRenderer::`RTTI Complete Object Locator'
PUBLIC	??_R3CRenderer@ssf@@8				; ssf::CRenderer::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CRenderer@ssf@@8				; ssf::CRenderer::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CRenderer@ssf@@8			; ssf::CRenderer::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCRenderer@ssf@@@8			; ssf::CRenderer `RTTI Type Descriptor'
PUBLIC	??0?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QAE@XZ	; ATL::CAutoPtr<ssf::SubtitleFile>::CAutoPtr<ssf::SubtitleFile>
PUBLIC	??0?$CAutoPtr@VRenderer@ssf@@@ATL@@QAE@XZ	; ATL::CAutoPtr<ssf::Renderer>::CAutoPtr<ssf::Renderer>
PUBLIC	??1?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QAE@XZ	; ATL::CAutoPtr<ssf::SubtitleFile>::~CAutoPtr<ssf::SubtitleFile>
PUBLIC	??1?$CAutoPtr@VRenderer@ssf@@@ATL@@QAE@XZ	; ATL::CAutoPtr<ssf::Renderer>::~CAutoPtr<ssf::Renderer>
PUBLIC	??_GCRenderer@ssf@@UAEPAXI@Z			; ssf::CRenderer::`scalar deleting destructor'
PUBLIC	?QueryInterface@CRenderer@ssf@@UAGJABU_GUID@@PAPAX@Z ; ssf::CRenderer::QueryInterface
PUBLIC	?QueryInterface@CRenderer@ssf@@W7AGJABU_GUID@@PAPAX@Z ; [thunk]:ssf::CRenderer::QueryInterface`adjustor{8}'
PUBLIC	?AddRef@CRenderer@ssf@@UAGKXZ			; ssf::CRenderer::AddRef
PUBLIC	?AddRef@CRenderer@ssf@@W7AGKXZ			; [thunk]:ssf::CRenderer::AddRef`adjustor{8}'
PUBLIC	?Release@CRenderer@ssf@@UAGKXZ			; ssf::CRenderer::Release
PUBLIC	?Release@CRenderer@ssf@@W7AGKXZ			; [thunk]:ssf::CRenderer::Release`adjustor{8}'
PUBLIC	?Attach@?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QAEXPAVSubtitleFile@ssf@@@Z ; ATL::CAutoPtr<ssf::SubtitleFile>::Attach
PUBLIC	?Free@?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QAEXXZ ; ATL::CAutoPtr<ssf::SubtitleFile>::Free
PUBLIC	?Attach@?$CAutoPtr@VRenderer@ssf@@@ATL@@QAEXPAVRenderer@ssf@@@Z ; ATL::CAutoPtr<ssf::Renderer>::Attach
PUBLIC	?Free@?$CAutoPtr@VRenderer@ssf@@@ATL@@QAEXXZ	; ATL::CAutoPtr<ssf::Renderer>::Free
PUBLIC	??1WCharInputStream@ssf@@UAE@XZ			; ssf::WCharInputStream::~WCharInputStream
PUBLIC	??B?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QBEPAVSubtitleFile@ssf@@XZ ; ATL::CAutoPtr<ssf::SubtitleFile>::operator ssf::SubtitleFile *
PUBLIC	??C?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QBEPAVSubtitleFile@ssf@@XZ ; ATL::CAutoPtr<ssf::SubtitleFile>::operator->
PUBLIC	??B?$CAutoPtr@VRenderer@ssf@@@ATL@@QBEPAVRenderer@ssf@@XZ ; ATL::CAutoPtr<ssf::Renderer>::operator ssf::Renderer *
PUBLIC	??C?$CAutoPtr@VRenderer@ssf@@@ATL@@QBEPAVRenderer@ssf@@XZ ; ATL::CAutoPtr<ssf::Renderer>::operator->
PUBLIC	?GetHeadPosition@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QBEPAU__POSITION@@XZ ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::GetHeadPosition
PUBLIC	?GetNext@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAEAAV?$CAutoPtr@VSubtitle@ssf@@@2@AAPAU__POSITION@@@Z ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::GetNext
PUBLIC	??0?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAE@I@Z ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >
PUBLIC	??0?$CAutoPtrList@VSubtitle@ssf@@@ATL@@QAE@I@Z	; ATL::CAutoPtrList<ssf::Subtitle>::CAutoPtrList<ssf::Subtitle>
PUBLIC	?Free@?$CAutoPtr@VSubtitle@ssf@@@ATL@@QAEXXZ	; ATL::CAutoPtr<ssf::Subtitle>::Free
PUBLIC	??1?$CAutoPtr@VSubtitle@ssf@@@ATL@@QAE@XZ	; ATL::CAutoPtr<ssf::Subtitle>::~CAutoPtr<ssf::Subtitle>
PUBLIC	??1CNode@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAE@XZ ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::CNode::~CNode
PUBLIC	??_GCNode@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAEPAXI@Z ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::CNode::`scalar deleting destructor'
PUBLIC	?FreeNode@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@AAEXPAVCNode@12@@Z ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::FreeNode
PUBLIC	?RemoveAll@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAEXXZ ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::RemoveAll
PUBLIC	??1?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAE@XZ ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::~CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >
PUBLIC	??1?$CAutoPtrList@VSubtitle@ssf@@@ATL@@QAE@XZ	; ATL::CAutoPtrList<ssf::Subtitle>::~CAutoPtrList<ssf::Subtitle>
PUBLIC	??B?$CAutoPtr@VSubtitle@ssf@@@ATL@@QBEPAVSubtitle@ssf@@XZ ; ATL::CAutoPtr<ssf::Subtitle>::operator ssf::Subtitle *
PUBLIC	??_R0?AVException@ssf@@@8			; ssf::Exception `RTTI Type Descriptor'
PUBLIC	??_7CRenderer@ssf@@6BCUnknown@@@		; ssf::CRenderer::`vftable'
PUBLIC	??_7CRenderer@ssf@@6BISubPicProviderEx@@@	; ssf::CRenderer::`vftable'
PUBLIC	??_7CRenderer@ssf@@6B@				; ssf::CRenderer::`vftable'
PUBLIC	__GUID_e0593632_0ab7_47ca_8be1_e9d2a6a4825e
EXTRN	??_ECRenderer@ssf@@UAEPAXI@Z:PROC		; ssf::CRenderer::`vector deleting destructor'
;	COMDAT __GUID_e0593632_0ab7_47ca_8be1_e9d2a6a4825e
CONST	SEGMENT
__GUID_e0593632_0ab7_47ca_8be1_e9d2a6a4825e DD 0e0593632H
	DW	0ab7H
	DW	047caH
	DB	08bH
	DB	0e1H
	DB	0e9H
	DB	0d2H
	DB	0a6H
	DB	0a4H
	DB	082H
	DB	05eH
CONST	ENDS
;	COMDAT ??_7CRenderer@ssf@@6B@
CONST	SEGMENT
??_7CRenderer@ssf@@6B@ DD FLAT:??_R4CRenderer@ssf@@6B@	; ssf::CRenderer::`vftable'
	DD	FLAT:?QueryInterface@CRenderer@ssf@@W7AGJABU_GUID@@PAPAX@Z
	DD	FLAT:?AddRef@CRenderer@ssf@@W7AGKXZ
	DD	FLAT:?Release@CRenderer@ssf@@W7AGKXZ
	DD	FLAT:?GetClassID@CRenderer@ssf@@UAGJPAU_GUID@@@Z
	DD	FLAT:?GetStreamCount@CRenderer@ssf@@UAGHXZ
	DD	FLAT:?GetStreamInfo@CRenderer@ssf@@UAGJHPAPA_WPAK@Z
	DD	FLAT:?GetStream@CRenderer@ssf@@UAGHXZ
	DD	FLAT:?SetStream@CRenderer@ssf@@UAGJH@Z
	DD	FLAT:?Reload@CRenderer@ssf@@UAGJXZ
CONST	ENDS
;	COMDAT ??_R4CRenderer@ssf@@6B@
rdata$r	SEGMENT
??_R4CRenderer@ssf@@6B@ DD 00H				; ssf::CRenderer::`RTTI Complete Object Locator'
	DD	014H
	DD	00H
	DD	FLAT:??_R0?AVCRenderer@ssf@@@8
	DD	FLAT:??_R3CRenderer@ssf@@8
rdata$r	ENDS
;	COMDAT ??_7CRenderer@ssf@@6BISubPicProviderEx@@@
CONST	SEGMENT
??_7CRenderer@ssf@@6BISubPicProviderEx@@@ DD FLAT:??_R4CRenderer@ssf@@6BISubPicProviderEx@@@ ; ssf::CRenderer::`vftable'
	DD	FLAT:?QueryInterface@CRenderer@ssf@@UAGJABU_GUID@@PAPAX@Z
	DD	FLAT:?AddRef@CRenderer@ssf@@UAGKXZ
	DD	FLAT:?Release@CRenderer@ssf@@UAGKXZ
	DD	FLAT:?Lock@CSubPicProviderImpl@@UAGJXZ
	DD	FLAT:?Unlock@CSubPicProviderImpl@@UAGJXZ
	DD	FLAT:?GetStartPosition@CRenderer@ssf@@UAGPAU__POSITION@@_JN@Z
	DD	FLAT:?GetNext@CRenderer@ssf@@UAGPAU__POSITION@@PAU3@@Z
	DD	FLAT:?GetStart@CRenderer@ssf@@UAG_JPAU__POSITION@@N@Z
	DD	FLAT:?GetStop@CRenderer@ssf@@UAG_JPAU__POSITION@@N@Z
	DD	FLAT:?IsAnimated@CRenderer@ssf@@UAG_NPAU__POSITION@@@Z
	DD	FLAT:?Render@CRenderer@ssf@@UAGJAAUSubPicDesc@@_JNAAUtagRECT@@@Z
	DD	FLAT:?GetTextureSize@CSubPicProviderImpl@@UAGJPAU__POSITION@@AAUtagSIZE@@1AAUtagPOINT@@@Z
	DD	FLAT:?GetStartStop@CSubPicProviderImpl@@UAGXPAU__POSITION@@NAA_J1@Z
	DD	FLAT:?RenderEx@CSubPicProviderImpl@@UAGJAAUSubPicDesc@@_JNAAV?$CAtlList@VCRect@@V?$CElementTraits@VCRect@@@ATL@@@ATL@@@Z
	DD	FLAT:?IsColorTypeSupported@CSubPicProviderImpl@@UAG_NH@Z
CONST	ENDS
;	COMDAT ??_R4CRenderer@ssf@@6BISubPicProviderEx@@@
rdata$r	SEGMENT
??_R4CRenderer@ssf@@6BISubPicProviderEx@@@ DD 00H	; ssf::CRenderer::`RTTI Complete Object Locator'
	DD	0cH
	DD	00H
	DD	FLAT:??_R0?AVCRenderer@ssf@@@8
	DD	FLAT:??_R3CRenderer@ssf@@8
rdata$r	ENDS
;	COMDAT ??_7CRenderer@ssf@@6BCUnknown@@@
CONST	SEGMENT
??_7CRenderer@ssf@@6BCUnknown@@@ DD FLAT:??_R4CRenderer@ssf@@6BCUnknown@@@ ; ssf::CRenderer::`vftable'
	DD	FLAT:?NonDelegatingQueryInterface@CRenderer@ssf@@UAGJABU_GUID@@PAPAX@Z
	DD	FLAT:?NonDelegatingAddRef@CUnknown@@UAGKXZ
	DD	FLAT:?NonDelegatingRelease@CUnknown@@UAGKXZ
	DD	FLAT:??_ECRenderer@ssf@@UAEPAXI@Z
CONST	ENDS
;	COMDAT ??_R4CRenderer@ssf@@6BCUnknown@@@
rdata$r	SEGMENT
??_R4CRenderer@ssf@@6BCUnknown@@@ DD 00H		; ssf::CRenderer::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVCRenderer@ssf@@@8
	DD	FLAT:??_R3CRenderer@ssf@@8
rdata$r	ENDS
;	COMDAT ??_R3CRenderer@ssf@@8
rdata$r	SEGMENT
??_R3CRenderer@ssf@@8 DD 00H				; ssf::CRenderer::`RTTI Class Hierarchy Descriptor'
	DD	05H
	DD	0bH
	DD	FLAT:??_R2CRenderer@ssf@@8
rdata$r	ENDS
;	COMDAT ??_R2CRenderer@ssf@@8
rdata$r	SEGMENT
??_R2CRenderer@ssf@@8 DD FLAT:??_R1A@?0A@EA@CRenderer@ssf@@8 ; ssf::CRenderer::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CSubPicProviderImpl@@8
	DD	FLAT:??_R1A@?0A@EA@CUnknown@@8
	DD	FLAT:??_R1A@?0A@EA@INonDelegatingUnknown@@8
	DD	FLAT:??_R13?0A@EA@CBaseObject@@8
	DD	FLAT:??_R1M@?0A@EA@ISubPicProviderEx@@8
	DD	FLAT:??_R1M@?0A@EA@ISubPicProvider@@8
	DD	FLAT:??_R1M@?0A@EC@IUnknown@@8
	DD	FLAT:??_R1BE@?0A@EA@ISubStream@@8
	DD	FLAT:??_R1BE@?0A@EA@IPersist@@8
	DD	FLAT:??_R1BE@?0A@EC@IUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CRenderer@ssf@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CRenderer@ssf@@8 DD FLAT:??_R0?AVCRenderer@ssf@@@8 ; ssf::CRenderer::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	0aH
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CRenderer@ssf@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCRenderer@ssf@@@8
_DATA	SEGMENT
??_R0?AVCRenderer@ssf@@@8 DD FLAT:??_7type_info@@6B@	; ssf::CRenderer `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCRenderer@ssf@@', 00H
_DATA	ENDS
;	COMDAT ??_R0?AVException@ssf@@@8
_DATA	SEGMENT
??_R0?AVException@ssf@@@8 DD FLAT:??_7type_info@@6B@	; ssf::Exception `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVException@ssf@@', 00H
; Function compile flags: /Ogtp
; File d:\program files (x86)\microsoft visual studio 10.0\vc\atlmfc\include\atlbase.h
;	COMDAT ?Free@?$CAutoPtr@VSubtitle@ssf@@@ATL@@QAEXXZ
_TEXT	SEGMENT
?Free@?$CAutoPtr@VSubtitle@ssf@@@ATL@@QAEXXZ PROC	; ATL::CAutoPtr<ssf::Subtitle>::Free, COMDAT
; _this$ = esi

; 887  : 		delete m_p;

	mov	ecx, DWORD PTR [esi]
	test	ecx, ecx
	je	SHORT $LN5@Free
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	push	1
	call	edx
$LN5@Free:

; 888  : 		m_p = NULL;

	mov	DWORD PTR [esi], 0

; 889  : 	}

	ret	0
?Free@?$CAutoPtr@VSubtitle@ssf@@@ATL@@QAEXXZ ENDP	; ATL::CAutoPtr<ssf::Subtitle>::Free
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ??1?$CAutoPtr@VSubtitle@ssf@@@ATL@@QAE@XZ
_TEXT	SEGMENT
??1?$CAutoPtr@VSubtitle@ssf@@@ATL@@QAE@XZ PROC		; ATL::CAutoPtr<ssf::Subtitle>::~CAutoPtr<ssf::Subtitle>, COMDAT
; _this$ = esi

; 794  : 		Free();

	mov	ecx, DWORD PTR [esi]
	test	ecx, ecx
	je	SHORT $LN7@CAutoPtr
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	push	1
	call	edx
$LN7@CAutoPtr:
	mov	DWORD PTR [esi], 0

; 795  : 	}

	ret	0
??1?$CAutoPtr@VSubtitle@ssf@@@ATL@@QAE@XZ ENDP		; ATL::CAutoPtr<ssf::Subtitle>::~CAutoPtr<ssf::Subtitle>
; Function compile flags: /Ogtp
; File d:\program files (x86)\microsoft visual studio 10.0\vc\atlmfc\include\atlcoll.h
_TEXT	ENDS
;	COMDAT ??1CNode@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAE@XZ
_TEXT	SEGMENT
??1CNode@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAE@XZ PROC ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::CNode::~CNode, COMDAT
; _this$ = esi

; 1190 : 		}

	mov	ecx, DWORD PTR [esi+8]
	test	ecx, ecx
	je	SHORT $LN9@CNode
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	push	1
	call	edx
$LN9@CNode:
	mov	DWORD PTR [esi+8], 0
	ret	0
??1CNode@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAE@XZ ENDP ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::CNode::~CNode
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ??_GCNode@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAEPAXI@Z
_TEXT	SEGMENT
??_GCNode@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAEPAXI@Z PROC ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::CNode::`scalar deleting destructor', COMDAT
; _this$ = esi
	mov	ecx, DWORD PTR [esi+8]
	test	ecx, ecx
	je	SHORT $LN12@scalar@2
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	push	1
	call	edx
$LN12@scalar@2:
	mov	eax, esi
	mov	DWORD PTR [esi+8], 0
	ret	0
??_GCNode@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAEPAXI@Z ENDP ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::CNode::`scalar deleting destructor'
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ?GetHeadPosition@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QBEPAU__POSITION@@XZ
_TEXT	SEGMENT
?GetHeadPosition@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QBEPAU__POSITION@@XZ PROC ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::GetHeadPosition, COMDAT
; _this$ = eax

; 1382 : 	return( POSITION( m_pHead ) );

	mov	eax, DWORD PTR [eax]

; 1383 : }

	ret	0
?GetHeadPosition@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QBEPAU__POSITION@@XZ ENDP ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::GetHeadPosition
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ??0?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAE@I@Z
_TEXT	SEGMENT
??0?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAE@I@Z PROC ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >, COMDAT
; _this$ = eax

; 1473 : {

	xor	ecx, ecx
	mov	DWORD PTR [eax], ecx
	mov	DWORD PTR [eax+4], ecx
	mov	DWORD PTR [eax+8], ecx
	mov	DWORD PTR [eax+12], ecx
	mov	DWORD PTR [eax+16], ecx
	mov	DWORD PTR [eax+20], 10			; 0000000aH

; 1474 : 	ATLASSERT( nBlockSize > 0 );
; 1475 : }

	ret	0
??0?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAE@I@Z ENDP ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >
; Function compile flags: /Ogtp
; File d:\program files (x86)\microsoft visual studio 10.0\vc\atlmfc\include\atlbase.h
_TEXT	ENDS
;	COMDAT ??B?$CAutoPtr@VSubtitle@ssf@@@ATL@@QBEPAVSubtitle@ssf@@XZ
_TEXT	SEGMENT
??B?$CAutoPtr@VSubtitle@ssf@@@ATL@@QBEPAVSubtitle@ssf@@XZ PROC ; ATL::CAutoPtr<ssf::Subtitle>::operator ssf::Subtitle *, COMDAT
; _this$ = eax

; 860  : 		return( m_p );

	mov	eax, DWORD PTR [eax]

; 861  : 	}

	ret	0
??B?$CAutoPtr@VSubtitle@ssf@@@ATL@@QBEPAVSubtitle@ssf@@XZ ENDP ; ATL::CAutoPtr<ssf::Subtitle>::operator ssf::Subtitle *
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ?Free@?$CAutoPtr@VRenderer@ssf@@@ATL@@QAEXXZ
_TEXT	SEGMENT
?Free@?$CAutoPtr@VRenderer@ssf@@@ATL@@QAEXXZ PROC	; ATL::CAutoPtr<ssf::Renderer>::Free, COMDAT
; _this$ = esi

; 887  : 		delete m_p;

	mov	ecx, DWORD PTR [esi]
	test	ecx, ecx
	je	SHORT $LN5@Free@2
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	push	1
	call	edx
$LN5@Free@2:

; 888  : 		m_p = NULL;

	mov	DWORD PTR [esi], 0

; 889  : 	}

	ret	0
?Free@?$CAutoPtr@VRenderer@ssf@@@ATL@@QAEXXZ ENDP	; ATL::CAutoPtr<ssf::Renderer>::Free
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ?Attach@?$CAutoPtr@VRenderer@ssf@@@ATL@@QAEXPAVRenderer@ssf@@@Z
_TEXT	SEGMENT
?Attach@?$CAutoPtr@VRenderer@ssf@@@ATL@@QAEXPAVRenderer@ssf@@@Z PROC ; ATL::CAutoPtr<ssf::Renderer>::Attach, COMDAT
; _this$ = eax
; _p$ = ecx

; 871  : 		ATLASSUME( m_p == NULL );
; 872  : 		m_p = p;

	mov	DWORD PTR [eax], ecx

; 873  : 	}

	ret	0
?Attach@?$CAutoPtr@VRenderer@ssf@@@ATL@@QAEXPAVRenderer@ssf@@@Z ENDP ; ATL::CAutoPtr<ssf::Renderer>::Attach
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ??C?$CAutoPtr@VRenderer@ssf@@@ATL@@QBEPAVRenderer@ssf@@XZ
_TEXT	SEGMENT
??C?$CAutoPtr@VRenderer@ssf@@@ATL@@QBEPAVRenderer@ssf@@XZ PROC ; ATL::CAutoPtr<ssf::Renderer>::operator->, COMDAT
; _this$ = eax

; 864  : 		ATLASSUME( m_p != NULL );
; 865  : 		return( m_p );

	mov	eax, DWORD PTR [eax]

; 866  : 	}

	ret	0
??C?$CAutoPtr@VRenderer@ssf@@@ATL@@QBEPAVRenderer@ssf@@XZ ENDP ; ATL::CAutoPtr<ssf::Renderer>::operator->
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ??B?$CAutoPtr@VRenderer@ssf@@@ATL@@QBEPAVRenderer@ssf@@XZ
_TEXT	SEGMENT
??B?$CAutoPtr@VRenderer@ssf@@@ATL@@QBEPAVRenderer@ssf@@XZ PROC ; ATL::CAutoPtr<ssf::Renderer>::operator ssf::Renderer *, COMDAT
; _this$ = eax

; 860  : 		return( m_p );

	mov	eax, DWORD PTR [eax]

; 861  : 	}

	ret	0
??B?$CAutoPtr@VRenderer@ssf@@@ATL@@QBEPAVRenderer@ssf@@XZ ENDP ; ATL::CAutoPtr<ssf::Renderer>::operator ssf::Renderer *
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ??1?$CAutoPtr@VRenderer@ssf@@@ATL@@QAE@XZ
_TEXT	SEGMENT
??1?$CAutoPtr@VRenderer@ssf@@@ATL@@QAE@XZ PROC		; ATL::CAutoPtr<ssf::Renderer>::~CAutoPtr<ssf::Renderer>, COMDAT
; _this$ = esi

; 794  : 		Free();

	mov	ecx, DWORD PTR [esi]
	test	ecx, ecx
	je	SHORT $LN7@CAutoPtr@2
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	push	1
	call	edx
$LN7@CAutoPtr@2:
	mov	DWORD PTR [esi], 0

; 795  : 	}

	ret	0
??1?$CAutoPtr@VRenderer@ssf@@@ATL@@QAE@XZ ENDP		; ATL::CAutoPtr<ssf::Renderer>::~CAutoPtr<ssf::Renderer>
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ??0?$CAutoPtr@VRenderer@ssf@@@ATL@@QAE@XZ
_TEXT	SEGMENT
??0?$CAutoPtr@VRenderer@ssf@@@ATL@@QAE@XZ PROC		; ATL::CAutoPtr<ssf::Renderer>::CAutoPtr<ssf::Renderer>, COMDAT
; _this$ = eax

; 777  : 	{

	mov	DWORD PTR [eax], 0

; 778  : 	}

	ret	0
??0?$CAutoPtr@VRenderer@ssf@@@ATL@@QAE@XZ ENDP		; ATL::CAutoPtr<ssf::Renderer>::CAutoPtr<ssf::Renderer>
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ?Free@?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QAEXXZ
_TEXT	SEGMENT
?Free@?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QAEXXZ PROC	; ATL::CAutoPtr<ssf::SubtitleFile>::Free, COMDAT
; _this$ = esi

; 887  : 		delete m_p;

	mov	ecx, DWORD PTR [esi]
	test	ecx, ecx
	je	SHORT $LN5@Free@3
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	push	1
	call	edx
$LN5@Free@3:

; 888  : 		m_p = NULL;

	mov	DWORD PTR [esi], 0

; 889  : 	}

	ret	0
?Free@?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QAEXXZ ENDP	; ATL::CAutoPtr<ssf::SubtitleFile>::Free
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ?Attach@?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QAEXPAVSubtitleFile@ssf@@@Z
_TEXT	SEGMENT
?Attach@?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QAEXPAVSubtitleFile@ssf@@@Z PROC ; ATL::CAutoPtr<ssf::SubtitleFile>::Attach, COMDAT
; _this$ = eax
; _p$ = ecx

; 871  : 		ATLASSUME( m_p == NULL );
; 872  : 		m_p = p;

	mov	DWORD PTR [eax], ecx

; 873  : 	}

	ret	0
?Attach@?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QAEXPAVSubtitleFile@ssf@@@Z ENDP ; ATL::CAutoPtr<ssf::SubtitleFile>::Attach
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ??C?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QBEPAVSubtitleFile@ssf@@XZ
_TEXT	SEGMENT
??C?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QBEPAVSubtitleFile@ssf@@XZ PROC ; ATL::CAutoPtr<ssf::SubtitleFile>::operator->, COMDAT
; _this$ = eax

; 864  : 		ATLASSUME( m_p != NULL );
; 865  : 		return( m_p );

	mov	eax, DWORD PTR [eax]

; 866  : 	}

	ret	0
??C?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QBEPAVSubtitleFile@ssf@@XZ ENDP ; ATL::CAutoPtr<ssf::SubtitleFile>::operator->
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ??B?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QBEPAVSubtitleFile@ssf@@XZ
_TEXT	SEGMENT
??B?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QBEPAVSubtitleFile@ssf@@XZ PROC ; ATL::CAutoPtr<ssf::SubtitleFile>::operator ssf::SubtitleFile *, COMDAT
; _this$ = eax

; 860  : 		return( m_p );

	mov	eax, DWORD PTR [eax]

; 861  : 	}

	ret	0
??B?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QBEPAVSubtitleFile@ssf@@XZ ENDP ; ATL::CAutoPtr<ssf::SubtitleFile>::operator ssf::SubtitleFile *
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ??1?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QAE@XZ
_TEXT	SEGMENT
??1?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QAE@XZ PROC	; ATL::CAutoPtr<ssf::SubtitleFile>::~CAutoPtr<ssf::SubtitleFile>, COMDAT
; _this$ = esi

; 794  : 		Free();

	mov	ecx, DWORD PTR [esi]
	test	ecx, ecx
	je	SHORT $LN7@CAutoPtr@3
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	push	1
	call	edx
$LN7@CAutoPtr@3:
	mov	DWORD PTR [esi], 0

; 795  : 	}

	ret	0
??1?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QAE@XZ ENDP	; ATL::CAutoPtr<ssf::SubtitleFile>::~CAutoPtr<ssf::SubtitleFile>
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ??0?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QAE@XZ
_TEXT	SEGMENT
??0?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QAE@XZ PROC	; ATL::CAutoPtr<ssf::SubtitleFile>::CAutoPtr<ssf::SubtitleFile>, COMDAT
; _this$ = eax

; 777  : 	{

	mov	DWORD PTR [eax], 0

; 778  : 	}

	ret	0
??0?$CAutoPtr@VSubtitleFile@ssf@@@ATL@@QAE@XZ ENDP	; ATL::CAutoPtr<ssf::SubtitleFile>::CAutoPtr<ssf::SubtitleFile>
; Function compile flags: /Ogtp
; File e:\github\codesandnotes\xy-vsfilter\src\subtitles\ssf.cpp
_TEXT	ENDS
;	COMDAT ?SetStream@CRenderer@ssf@@UAGJH@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_iStream$ = 12						; size = 4
?SetStream@CRenderer@ssf@@UAGJH@Z PROC			; ssf::CRenderer::SetStream, COMDAT

; 228  : 	{

	push	ebp
	mov	ebp, esp

; 229  : 		return iStream == 0 ? S_OK : E_FAIL;

	mov	eax, DWORD PTR _iStream$[ebp]
	neg	eax
	sbb	eax, eax
	and	eax, -2147467259			; 80004005H

; 230  : 	}

	pop	ebp
	ret	8
?SetStream@CRenderer@ssf@@UAGJH@Z ENDP			; ssf::CRenderer::SetStream
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ?GetStream@CRenderer@ssf@@UAGHXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetStream@CRenderer@ssf@@UAGHXZ PROC			; ssf::CRenderer::GetStream, COMDAT

; 224  : 		return 0;

	xor	eax, eax

; 225  : 	}

	ret	4
?GetStream@CRenderer@ssf@@UAGHXZ ENDP			; ssf::CRenderer::GetStream
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ?GetStreamCount@CRenderer@ssf@@UAGHXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetStreamCount@CRenderer@ssf@@UAGHXZ PROC		; ssf::CRenderer::GetStreamCount, COMDAT

; 199  : 		return 1;

	mov	eax, 1

; 200  : 	}

	ret	4
?GetStreamCount@CRenderer@ssf@@UAGHXZ ENDP		; ssf::CRenderer::GetStreamCount
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ?GetClassID@CRenderer@ssf@@UAGJPAU_GUID@@@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_pClassID$ = 12						; size = 4
?GetClassID@CRenderer@ssf@@UAGJPAU_GUID@@@Z PROC	; ssf::CRenderer::GetClassID, COMDAT

; 191  : 	{

	push	ebp
	mov	ebp, esp

; 192  : 		return pClassID ? *pClassID = __uuidof(this), S_OK : E_POINTER;

	mov	eax, DWORD PTR _pClassID$[ebp]
	test	eax, eax
	je	SHORT $LN3@GetClassID
	mov	ecx, DWORD PTR __GUID_e0593632_0ab7_47ca_8be1_e9d2a6a4825e
	mov	DWORD PTR [eax], ecx
	mov	edx, DWORD PTR __GUID_e0593632_0ab7_47ca_8be1_e9d2a6a4825e+4
	mov	DWORD PTR [eax+4], edx
	mov	ecx, DWORD PTR __GUID_e0593632_0ab7_47ca_8be1_e9d2a6a4825e+8
	mov	DWORD PTR [eax+8], ecx
	mov	edx, DWORD PTR __GUID_e0593632_0ab7_47ca_8be1_e9d2a6a4825e+12
	mov	DWORD PTR [eax+12], edx
	xor	eax, eax

; 193  : 	}

	pop	ebp
	ret	8
$LN3@GetClassID:

; 192  : 		return pClassID ? *pClassID = __uuidof(this), S_OK : E_POINTER;

	mov	eax, -2147467261			; 80004003H

; 193  : 	}

	pop	ebp
	ret	8
?GetClassID@CRenderer@ssf@@UAGJPAU_GUID@@@Z ENDP	; ssf::CRenderer::GetClassID
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ?IsAnimated@CRenderer@ssf@@UAG_NPAU__POSITION@@@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_pos$ = 12						; size = 4
?IsAnimated@CRenderer@ssf@@UAG_NPAU__POSITION@@@Z PROC	; ssf::CRenderer::IsAnimated, COMDAT

; 155  : 		return true;

	mov	al, 1

; 156  : 	}

	ret	8
?IsAnimated@CRenderer@ssf@@UAG_NPAU__POSITION@@@Z ENDP	; ssf::CRenderer::IsAnimated
; Function compile flags: /Ogtp
; File d:\program files (x86)\microsoft visual studio 10.0\vc\atlmfc\include\atlcoll.h
;	COMDAT ?RemoveAll@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAEXXZ
_TEXT	SEGMENT
?RemoveAll@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAEXXZ PROC ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::RemoveAll, COMDAT
; _this$ = esi

; 1480 : 	while( m_nElements > 0 )

	cmp	DWORD PTR [esi+8], 0
	jbe	SHORT $LN7@RemoveAll@3
$LL19@RemoveAll@3:

; 1481 : 	{
; 1482 : 		CNode* pKill = m_pHead;

	mov	eax, DWORD PTR [esi]

; 1483 : 		ATLENSURE( pKill != NULL );

	test	eax, eax
	je	SHORT $LN48@RemoveAll@3

; 1484 : 
; 1485 : 		m_pHead = m_pHead->m_pNext;

	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR [esi], ecx

; 1486 : 		FreeNode( pKill );

	push	eax
	mov	ecx, esi
	call	?FreeNode@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@AAEXPAVCNode@12@@Z ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::FreeNode
	cmp	DWORD PTR [esi+8], 0
	ja	SHORT $LL19@RemoveAll@3
$LN7@RemoveAll@3:

; 1487 : 	}
; 1488 : 
; 1489 : 	ATLASSUME( m_nElements == 0 );
; 1490 : 	m_pHead = NULL;
; 1491 : 	m_pTail = NULL;
; 1492 : 	m_pFree = NULL;
; 1493 : 
; 1494 : 	if( m_pBlocks != NULL )

	mov	eax, DWORD PTR [esi+12]
	mov	DWORD PTR [esi], 0
	mov	DWORD PTR [esi+4], 0
	mov	DWORD PTR [esi+16], 0
	test	eax, eax
	je	SHORT $LN1@RemoveAll@3
	push	edi
	npad	6

; 1495 : 	{
; 1496 : 		m_pBlocks->FreeDataChain();

$LL43@RemoveAll@3:
	mov	edi, DWORD PTR [eax]
	push	eax
	call	_free
	add	esp, 4
	mov	eax, edi
	test	edi, edi
	jne	SHORT $LL43@RemoveAll@3

; 1497 : 		m_pBlocks = NULL;

	mov	DWORD PTR [esi+12], edi
	pop	edi
$LN1@RemoveAll@3:

; 1498 : 	}
; 1499 : }

	ret	0
$LN48@RemoveAll@3:

; 1483 : 		ATLENSURE( pKill != NULL );

	push	-2147467259				; 80004005H
	call	?AtlThrowImpl@ATL@@YGXJ@Z		; ATL::AtlThrowImpl
$LN52@RemoveAll@3:
$LN51@RemoveAll@3:
	int	3
?RemoveAll@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAEXXZ ENDP ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::RemoveAll
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ??1?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAE@XZ
_TEXT	SEGMENT
??1?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAE@XZ PROC ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::~CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >, COMDAT
; _this$ = esi

; 1504 : 	RemoveAll();

	jmp	?RemoveAll@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAEXXZ ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::RemoveAll
??1?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAE@XZ ENDP ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::~CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ?GetNext@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAEAAV?$CAutoPtr@VSubtitle@ssf@@@2@AAPAU__POSITION@@@Z
_TEXT	SEGMENT
?GetNext@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAEAAV?$CAutoPtr@VSubtitle@ssf@@@2@AAPAU__POSITION@@@Z PROC ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::GetNext, COMDAT
; _pos$ = ecx

; 1394 : 	CNode* pNode;
; 1395 : 
; 1396 : 	ATLENSURE( pos != NULL );

	mov	eax, DWORD PTR [ecx]
	test	eax, eax
	jne	SHORT $LN9@GetNext@6
	push	-2147467259				; 80004005H
	call	?AtlThrowImpl@ATL@@YGXJ@Z		; ATL::AtlThrowImpl
$LN14@GetNext@6:
$LN9@GetNext@6:

; 1397 : 	pNode = (CNode*)pos;
; 1398 : 	pos = POSITION( pNode->m_pNext );

	mov	edx, DWORD PTR [eax]
	mov	DWORD PTR [ecx], edx

; 1399 : 
; 1400 : 	return( pNode->m_element );

	add	eax, 8

; 1401 : }

	ret	0
$LN13@GetNext@6:
?GetNext@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAEAAV?$CAutoPtr@VSubtitle@ssf@@@2@AAPAU__POSITION@@@Z ENDP ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::GetNext
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ??0?$CAutoPtrList@VSubtitle@ssf@@@ATL@@QAE@I@Z
_TEXT	SEGMENT
??0?$CAutoPtrList@VSubtitle@ssf@@@ATL@@QAE@I@Z PROC	; ATL::CAutoPtrList<ssf::Subtitle>::CAutoPtrList<ssf::Subtitle>, COMDAT
; _this$ = eax

; 1314 : 	{

	xor	ecx, ecx
	mov	DWORD PTR [eax], ecx
	mov	DWORD PTR [eax+4], ecx
	mov	DWORD PTR [eax+8], ecx
	mov	DWORD PTR [eax+12], ecx
	mov	DWORD PTR [eax+16], ecx
	mov	DWORD PTR [eax+20], 10			; 0000000aH

; 1315 : 	}

	ret	0
??0?$CAutoPtrList@VSubtitle@ssf@@@ATL@@QAE@I@Z ENDP	; ATL::CAutoPtrList<ssf::Subtitle>::CAutoPtrList<ssf::Subtitle>
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ??1?$CAutoPtrList@VSubtitle@ssf@@@ATL@@QAE@XZ
_TEXT	SEGMENT
??1?$CAutoPtrList@VSubtitle@ssf@@@ATL@@QAE@XZ PROC	; ATL::CAutoPtrList<ssf::Subtitle>::~CAutoPtrList<ssf::Subtitle>, COMDAT
; _this$ = esi
	jmp	?RemoveAll@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAEXXZ ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::RemoveAll
??1?$CAutoPtrList@VSubtitle@ssf@@@ATL@@QAE@XZ ENDP	; ATL::CAutoPtrList<ssf::Subtitle>::~CAutoPtrList<ssf::Subtitle>
_TEXT	ENDS
PUBLIC	__real@416312d000000000
EXTRN	__ftol2:PROC
;	COMDAT __real@416312d000000000
CONST	SEGMENT
__real@416312d000000000 DQ 0416312d000000000r	; 1e+007
; Function compile flags: /Ogtp
; File e:\github\codesandnotes\xy-vsfilter\src\subtitles\ssf.cpp
CONST	ENDS
;	COMDAT ?GetStop@CRenderer@ssf@@UAG_JPAU__POSITION@@N@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_pos$ = 12						; size = 4
_fps$ = 16						; size = 8
?GetStop@CRenderer@ssf@@UAG_JPAU__POSITION@@N@Z PROC	; ssf::CRenderer::GetStop, COMDAT

; 145  : 	{

	push	ebp
	mov	ebp, esp

; 146  : 		CheckPointer(m_file, 0);

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+20]
	test	eax, eax
	je	SHORT $LN6@GetStop

; 147  : 
; 148  : 		size_t k = (size_t)pos-1;

	mov	ecx, DWORD PTR _pos$[ebp]
	dec	ecx

; 149  : 		const SubtitleFile::Segment* s = m_file ? m_file->m_segments.GetSegment(k) : NULL;

	cmp	ecx, DWORD PTR [eax+124]
	jae	SHORT $LN22@GetStop
	mov	edx, DWORD PTR [eax+120]
	mov	ecx, DWORD PTR [edx+ecx*4]
	jmp	SHORT $LN23@GetStop
$LN22@GetStop:
	xor	ecx, ecx
$LN23@GetStop:

; 150  : 		return s ? (REFERENCE_TIME)(s->m_stop*10000000) : 0;

	test	ecx, ecx
	je	SHORT $LN6@GetStop
	fld	DWORD PTR [ecx+28]
	fmul	QWORD PTR __real@416312d000000000
	call	__ftol2

; 151  : 	}

	pop	ebp
	ret	16					; 00000010H
$LN6@GetStop:

; 150  : 		return s ? (REFERENCE_TIME)(s->m_stop*10000000) : 0;

	xor	eax, eax
	xor	edx, edx

; 151  : 	}

	pop	ebp
	ret	16					; 00000010H
?GetStop@CRenderer@ssf@@UAG_JPAU__POSITION@@N@Z ENDP	; ssf::CRenderer::GetStop
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ?GetStart@CRenderer@ssf@@UAG_JPAU__POSITION@@N@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_pos$ = 12						; size = 4
_fps$ = 16						; size = 8
?GetStart@CRenderer@ssf@@UAG_JPAU__POSITION@@N@Z PROC	; ssf::CRenderer::GetStart, COMDAT

; 138  : 	{

	push	ebp
	mov	ebp, esp

; 139  : 		size_t k = (size_t)pos-1;
; 140  : 		const SubtitleFile::Segment* s = m_file ? m_file->m_segments.GetSegment(k) : NULL;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _pos$[ebp]
	mov	eax, DWORD PTR [eax+20]
	dec	ecx
	test	eax, eax
	je	SHORT $LN3@GetStart
	cmp	ecx, DWORD PTR [eax+124]
	jae	SHORT $LN3@GetStart
	mov	edx, DWORD PTR [eax+120]
	mov	eax, DWORD PTR [edx+ecx*4]
	jmp	SHORT $LN4@GetStart
$LN3@GetStart:
	xor	eax, eax
$LN4@GetStart:

; 141  : 		return s ? (REFERENCE_TIME)(s->m_start*10000000) : 0;

	test	eax, eax
	je	SHORT $LN5@GetStart
	fld	DWORD PTR [eax+24]
	fmul	QWORD PTR __real@416312d000000000
	call	__ftol2

; 142  : 	}

	pop	ebp
	ret	16					; 00000010H
$LN5@GetStart:

; 141  : 		return s ? (REFERENCE_TIME)(s->m_start*10000000) : 0;

	xor	eax, eax
	xor	edx, edx

; 142  : 	}

	pop	ebp
	ret	16					; 00000010H
?GetStart@CRenderer@ssf@@UAG_JPAU__POSITION@@N@Z ENDP	; ssf::CRenderer::GetStart
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ?GetNext@CRenderer@ssf@@UAGPAU__POSITION@@PAU3@@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_pos$ = 12						; size = 4
?GetNext@CRenderer@ssf@@UAGPAU__POSITION@@PAU3@@Z PROC	; ssf::CRenderer::GetNext, COMDAT

; 132  : 	{

	push	ebp
	mov	ebp, esp

; 133  : 		size_t k = (size_t)pos;
; 134  : 		return m_file && m_file->m_segments.GetSegment(k) ? (POSITION)(++k) : NULL;

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+20]
	test	eax, eax
	je	SHORT $LN3@GetNext@7
	mov	ecx, DWORD PTR _pos$[ebp]
	cmp	ecx, DWORD PTR [eax+124]
	jae	SHORT $LN3@GetNext@7
	mov	edx, DWORD PTR [eax+120]
	cmp	DWORD PTR [edx+ecx*4], 0
	je	SHORT $LN3@GetNext@7
	lea	eax, DWORD PTR [ecx+1]

; 135  : 	}

	pop	ebp
	ret	8
$LN3@GetNext@7:

; 133  : 		size_t k = (size_t)pos;
; 134  : 		return m_file && m_file->m_segments.GetSegment(k) ? (POSITION)(++k) : NULL;

	xor	eax, eax

; 135  : 	}

	pop	ebp
	ret	8
?GetNext@CRenderer@ssf@@UAGPAU__POSITION@@PAU3@@Z ENDP	; ssf::CRenderer::GetNext
_TEXT	ENDS
PUBLIC	??1CRenderer@ssf@@UAE@XZ			; ssf::CRenderer::~CRenderer
; Function compile flags: /Ogtp
;	COMDAT ??1CRenderer@ssf@@UAE@XZ
_TEXT	SEGMENT
??1CRenderer@ssf@@UAE@XZ PROC				; ssf::CRenderer::~CRenderer, COMDAT
; _this$ = ecx

; 39   : 	{

	push	esi
	mov	esi, ecx
	mov	DWORD PTR [esi], OFFSET ??_7CRenderer@ssf@@6BCUnknown@@@
	mov	DWORD PTR [esi+12], OFFSET ??_7CRenderer@ssf@@6BISubPicProviderEx@@@
	mov	DWORD PTR [esi+20], OFFSET ??_7CRenderer@ssf@@6B@

; 40   : 	}

	mov	ecx, DWORD PTR [esi+36]
	test	ecx, ecx
	je	SHORT $LN7@CRenderer
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	push	1
	call	edx
$LN7@CRenderer:
	mov	DWORD PTR [esi+36], 0
	mov	ecx, DWORD PTR [esi+32]
	test	ecx, ecx
	je	SHORT $LN13@CRenderer
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	push	1
	call	edx
$LN13@CRenderer:
	mov	DWORD PTR [esi+32], 0
	mov	eax, DWORD PTR [esi+28]
	sub	eax, 16					; 00000010H
	lea	ecx, DWORD PTR [eax+12]
	or	edx, -1
	lock	 xadd	 DWORD PTR [ecx], edx
	dec	edx
	test	edx, edx
	jg	SHORT $LN21@CRenderer
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	push	eax
	mov	eax, DWORD PTR [edx+4]
	call	eax
$LN21@CRenderer:
	mov	eax, DWORD PTR [esi+24]
	sub	eax, 16					; 00000010H
	lea	ecx, DWORD PTR [eax+12]
	or	edx, -1
	lock	 xadd	 DWORD PTR [ecx], edx
	dec	edx
	test	edx, edx
	jg	SHORT $LN30@CRenderer
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	push	eax
	mov	eax, DWORD PTR [edx+4]
	call	eax
$LN30@CRenderer:
	push	OFFSET ?m_cObjects@CBaseObject@@0JA	; CBaseObject::m_cObjects
	mov	DWORD PTR [esi], OFFSET ??_7CSubPicProviderImpl@@6BCUnknown@@@
	mov	DWORD PTR [esi+12], OFFSET ??_7CSubPicProviderImpl@@6BISubPicProviderEx@@@
	call	DWORD PTR __imp__InterlockedDecrement@4
	pop	esi
	test	eax, eax
	jne	SHORT $LN37@CRenderer
	mov	eax, DWORD PTR ?hlibOLEAut32@@3PAUHINSTANCE__@@A ; hlibOLEAut32
	test	eax, eax
	je	SHORT $LN37@CRenderer
	push	eax
	call	DWORD PTR __imp__FreeLibrary@4
	mov	DWORD PTR ?hlibOLEAut32@@3PAUHINSTANCE__@@A, 0 ; hlibOLEAut32
$LN37@CRenderer:
	ret	0
??1CRenderer@ssf@@UAE@XZ ENDP				; ssf::CRenderer::~CRenderer
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ??_GCRenderer@ssf@@UAEPAXI@Z
_TEXT	SEGMENT
___flags$ = 8						; size = 4
??_GCRenderer@ssf@@UAEPAXI@Z PROC			; ssf::CRenderer::`scalar deleting destructor', COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, ecx
	call	??1CRenderer@ssf@@UAE@XZ		; ssf::CRenderer::~CRenderer
	test	BYTE PTR ___flags$[ebp], 1
	je	SHORT $LN4@scalar@26
	push	esi
	call	??3@YAXPAX@Z				; operator delete
	add	esp, 4
$LN4@scalar@26:
	mov	eax, esi
	pop	esi
	pop	ebp
	ret	4
??_GCRenderer@ssf@@UAEPAXI@Z ENDP			; ssf::CRenderer::`scalar deleting destructor'
; Function compile flags: /Ogtp
; File e:\github\codesandnotes\xy-vsfilter\src\subtitles\ssf.h
_TEXT	ENDS
;	COMDAT ?Release@CRenderer@ssf@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?Release@CRenderer@ssf@@UAGKXZ PROC			; ssf::CRenderer::Release, COMDAT

; 48   :         DECLARE_IUNKNOWN

	push	ebp
	mov	ebp, esp
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax-8]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx+8]
	push	eax
	call	edx
	pop	ebp
	ret	4
?Release@CRenderer@ssf@@UAGKXZ ENDP			; ssf::CRenderer::Release
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ?AddRef@CRenderer@ssf@@UAGKXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?AddRef@CRenderer@ssf@@UAGKXZ PROC			; ssf::CRenderer::AddRef, COMDAT

; 48   :         DECLARE_IUNKNOWN

	push	ebp
	mov	ebp, esp
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax-8]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx+4]
	push	eax
	call	edx
	pop	ebp
	ret	4
?AddRef@CRenderer@ssf@@UAGKXZ ENDP			; ssf::CRenderer::AddRef
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ?QueryInterface@CRenderer@ssf@@UAGJABU_GUID@@PAPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_riid$ = 12						; size = 4
_ppv$ = 16						; size = 4
?QueryInterface@CRenderer@ssf@@UAGJABU_GUID@@PAPAX@Z PROC ; ssf::CRenderer::QueryInterface, COMDAT

; 48   :         DECLARE_IUNKNOWN

	push	ebp
	mov	ebp, esp
	mov	edx, DWORD PTR _ppv$[ebp]
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax-8]
	mov	ecx, DWORD PTR [eax]
	push	edx
	mov	edx, DWORD PTR _riid$[ebp]
	push	edx
	push	eax
	mov	eax, DWORD PTR [ecx]
	call	eax
	pop	ebp
	ret	12					; 0000000cH
?QueryInterface@CRenderer@ssf@@UAGJABU_GUID@@PAPAX@Z ENDP ; ssf::CRenderer::QueryInterface
; Function compile flags: /Odtp
;	COMDAT ?Release@CRenderer@ssf@@W7AGKXZ
_TEXT	SEGMENT
?Release@CRenderer@ssf@@W7AGKXZ PROC			; [thunk]:ssf::CRenderer::Release`adjustor{8}', COMDAT
	sub	DWORD PTR [esp+4], 8
	jmp	?Release@CRenderer@ssf@@UAGKXZ		; ssf::CRenderer::Release
?Release@CRenderer@ssf@@W7AGKXZ ENDP			; [thunk]:ssf::CRenderer::Release`adjustor{8}'
; Function compile flags: /Odtp
_TEXT	ENDS
;	COMDAT ?QueryInterface@CRenderer@ssf@@W7AGJABU_GUID@@PAPAX@Z
_TEXT	SEGMENT
?QueryInterface@CRenderer@ssf@@W7AGJABU_GUID@@PAPAX@Z PROC ; [thunk]:ssf::CRenderer::QueryInterface`adjustor{8}', COMDAT
	sub	DWORD PTR [esp+4], 8
	jmp	?QueryInterface@CRenderer@ssf@@UAGJABU_GUID@@PAPAX@Z ; ssf::CRenderer::QueryInterface
?QueryInterface@CRenderer@ssf@@W7AGJABU_GUID@@PAPAX@Z ENDP ; [thunk]:ssf::CRenderer::QueryInterface`adjustor{8}'
; Function compile flags: /Odtp
_TEXT	ENDS
;	COMDAT ?AddRef@CRenderer@ssf@@W7AGKXZ
_TEXT	SEGMENT
?AddRef@CRenderer@ssf@@W7AGKXZ PROC			; [thunk]:ssf::CRenderer::AddRef`adjustor{8}', COMDAT
	sub	DWORD PTR [esp+4], 8
	jmp	?AddRef@CRenderer@ssf@@UAGKXZ		; ssf::CRenderer::AddRef
?AddRef@CRenderer@ssf@@W7AGKXZ ENDP			; [thunk]:ssf::CRenderer::AddRef`adjustor{8}'
; Function compile flags: /Ogtp
; File d:\program files (x86)\microsoft visual studio 10.0\vc\atlmfc\include\atlcoll.h
_TEXT	ENDS
;	COMDAT ?FreeNode@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@AAEXPAVCNode@12@@Z
_TEXT	SEGMENT
_pNode$ = 8						; size = 4
?FreeNode@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@AAEXPAVCNode@12@@Z PROC ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::FreeNode, COMDAT
; _this$ = ecx

; 1583 : {

	push	ebp
	mov	ebp, esp
	push	esi
	push	edi

; 1584 : 	pNode->~CNode();

	mov	edi, DWORD PTR _pNode$[ebp]
	mov	esi, ecx
	mov	ecx, DWORD PTR [edi+8]
	test	ecx, ecx
	je	SHORT $LN19@FreeNode@9
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	push	1
	call	edx
$LN19@FreeNode@9:
	mov	DWORD PTR [edi+8], 0

; 1585 : 	pNode->m_pNext = m_pFree;

	mov	eax, DWORD PTR [esi+16]
	mov	DWORD PTR [edi], eax

; 1586 : 	m_pFree = pNode;
; 1587 : 	ATLASSUME( m_nElements > 0 );
; 1588 : 	m_nElements--;

	dec	DWORD PTR [esi+8]
	mov	DWORD PTR [esi+16], edi

; 1589 : 	if( m_nElements == 0 )

	jne	SHORT $LN1@FreeNode@9

; 1590 : 	{
; 1591 : 		RemoveAll();

	call	?RemoveAll@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAEXXZ ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::RemoveAll
$LN1@FreeNode@9:
	pop	edi
	pop	esi

; 1592 : 	}
; 1593 : }

	pop	ebp
	ret	4
?FreeNode@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@AAEXPAVCNode@12@@Z ENDP ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::FreeNode
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ??1WCharInputStream@ssf@@UAE@XZ
_TEXT	SEGMENT
??1WCharInputStream@ssf@@UAE@XZ PROC			; ssf::WCharInputStream::~WCharInputStream, COMDAT
; _this$ = edi
	mov	eax, DWORD PTR [edi+40]
	sub	eax, 16					; 00000010H
	lea	ecx, DWORD PTR [eax+12]
	or	edx, -1
	lock	 xadd	 DWORD PTR [ecx], edx
	dec	edx
	test	edx, edx
	jg	SHORT $LN9@WCharInput
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	push	eax
	mov	eax, DWORD PTR [edx+4]
	call	eax
$LN9@WCharInput:
	push	esi
	lea	esi, DWORD PTR [edi+16]
	mov	DWORD PTR [edi], OFFSET ??_7InputStream@ssf@@6B@
	call	?RemoveAll@?$CAtlList@HV?$CElementTraits@H@ATL@@@ATL@@QAEXXZ ; ATL::CAtlList<int,ATL::CElementTraits<int> >::RemoveAll
	mov	DWORD PTR [edi], OFFSET ??_7Stream@ssf@@6B@
	pop	esi
	ret	0
??1WCharInputStream@ssf@@UAE@XZ ENDP			; ssf::WCharInputStream::~WCharInputStream
; Function compile flags: /Ogtp
; File e:\github\codesandnotes\xy-vsfilter\src\subtitles\ssf.cpp
;	COMDAT ?GetStartPosition@CRenderer@ssf@@UAGPAU__POSITION@@_JN@Z
_TEXT	SEGMENT
tv144 = 8						; size = 4
_k$ = 8							; size = 4
_this$ = 8						; size = 4
_rt$ = 12						; size = 8
_fps$ = 20						; size = 8
?GetStartPosition@CRenderer@ssf@@UAGPAU__POSITION@@_JN@Z PROC ; ssf::CRenderer::GetStartPosition, COMDAT

; 126  : 	{

	push	ebp
	mov	ebp, esp

; 127  : 		size_t k;
; 128  : 		return m_file && m_file->m_segments.Lookup((float)rt/10000000, k) ? (POSITION)(++k) : NULL;

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+20]
	test	eax, eax
	je	SHORT $LN3@GetStartPo@8
	fild	QWORD PTR _rt$[ebp]
	lea	ecx, DWORD PTR _k$[ebp]
	push	ecx
	push	ecx
	fdiv	QWORD PTR __real@416312d000000000
	add	eax, 96					; 00000060H
	fstp	DWORD PTR tv144[ebp]
	fld	DWORD PTR tv144[ebp]
	fstp	DWORD PTR [esp]
	call	?Lookup@SegmentList@SubtitleFile@ssf@@QAE_NMAAI@Z ; ssf::SubtitleFile::SegmentList::Lookup
	test	al, al
	je	SHORT $LN3@GetStartPo@8
	mov	eax, DWORD PTR _k$[ebp]
	inc	eax

; 129  : 	}

	pop	ebp
	ret	20					; 00000014H
$LN3@GetStartPo@8:

; 127  : 		size_t k;
; 128  : 		return m_file && m_file->m_segments.Lookup((float)rt/10000000, k) ? (POSITION)(++k) : NULL;

	xor	eax, eax

; 129  : 	}

	pop	ebp
	ret	20					; 00000014H
?GetStartPosition@CRenderer@ssf@@UAGPAU__POSITION@@_JN@Z ENDP ; ssf::CRenderer::GetStartPosition
; Function compile flags: /Ogtp
_TEXT	ENDS
;	COMDAT ?NonDelegatingQueryInterface@CRenderer@ssf@@UAGJABU_GUID@@PAPAX@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_riid$ = 12						; size = 4
_ppv$ = 16						; size = 4
?NonDelegatingQueryInterface@CRenderer@ssf@@UAGJABU_GUID@@PAPAX@Z PROC ; ssf::CRenderer::NonDelegatingQueryInterface, COMDAT

; 112  : 	{

	push	ebp
	mov	ebp, esp
	push	esi

; 113  : 		CheckPointer(ppv, E_POINTER);

	mov	esi, DWORD PTR _ppv$[ebp]
	test	esi, esi
	jne	SHORT $LN1@NonDelegat
	mov	eax, -2147467261			; 80004003H
	pop	esi

; 121  : 	}

	pop	ebp
	ret	12					; 0000000cH
$LN1@NonDelegat:
	push	edi

; 114  : 		*ppv = NULL;
; 115  : 
; 116  : 		return 
; 117  : 			QI(IPersist)
; 118  : 			QI(ISubStream)
; 119  : 			QI(ISubPicProvider)
; 120  : 			__super::NonDelegatingQueryInterface(riid, ppv);

	mov	edi, DWORD PTR _riid$[ebp]
	push	OFFSET __GUID_0000010c_0000_0000_c000_000000000046
	push	edi
	mov	DWORD PTR [esi], 0
	call	_IsEqualGUID
	add	esp, 8
	test	eax, eax
	jne	SHORT $LN31@NonDelegat
	push	OFFSET __GUID_de11e2fb_02d3_45e4_a174_6b7ce2783bdb
	push	edi
	call	_IsEqualGUID
	add	esp, 8
	test	eax, eax
	je	SHORT $LN12@NonDelegat
$LN31@NonDelegat:
	mov	eax, DWORD PTR _this$[ebp]
	test	eax, eax
	je	SHORT $LN8@NonDelegat
	add	eax, 20					; 00000014H
	mov	DWORD PTR [esi], eax
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx+4]
	push	eax
	call	edx
	pop	edi
	xor	eax, eax
	pop	esi

; 121  : 	}

	pop	ebp
	ret	12					; 0000000cH
$LN12@NonDelegat:

; 114  : 		*ppv = NULL;
; 115  : 
; 116  : 		return 
; 117  : 			QI(IPersist)
; 118  : 			QI(ISubStream)
; 119  : 			QI(ISubPicProvider)
; 120  : 			__super::NonDelegatingQueryInterface(riid, ppv);

	push	OFFSET __GUID_d62b9a1a_879a_42db_ab04_88aa8f243cfd
	push	edi
	call	_IsEqualGUID
	add	esp, 8
	test	eax, eax
	mov	eax, DWORD PTR _this$[ebp]
	je	SHORT $LN10@NonDelegat
	test	eax, eax
	je	SHORT $LN8@NonDelegat
	add	eax, 12					; 0000000cH
	mov	DWORD PTR [esi], eax
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx+4]
	push	eax
	call	edx
	pop	edi
	xor	eax, eax
	pop	esi

; 121  : 	}

	pop	ebp
	ret	12					; 0000000cH
$LN8@NonDelegat:

; 114  : 		*ppv = NULL;
; 115  : 
; 116  : 		return 
; 117  : 			QI(IPersist)
; 118  : 			QI(ISubStream)
; 119  : 			QI(ISubPicProvider)
; 120  : 			__super::NonDelegatingQueryInterface(riid, ppv);

	xor	eax, eax
	mov	DWORD PTR [esi], eax
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx+4]
	push	eax
	call	edx
	pop	edi
	xor	eax, eax
	pop	esi

; 121  : 	}

	pop	ebp
	ret	12					; 0000000cH
$LN10@NonDelegat:

; 114  : 		*ppv = NULL;
; 115  : 
; 116  : 		return 
; 117  : 			QI(IPersist)
; 118  : 			QI(ISubStream)
; 119  : 			QI(ISubPicProvider)
; 120  : 			__super::NonDelegatingQueryInterface(riid, ppv);

	push	esi
	push	edi
	push	eax
	call	?NonDelegatingQueryInterface@CSubPicProviderImpl@@UAGJABU_GUID@@PAPAX@Z ; CSubPicProviderImpl::NonDelegatingQueryInterface
	pop	edi
	pop	esi

; 121  : 	}

	pop	ebp
	ret	12					; 0000000cH
?NonDelegatingQueryInterface@CRenderer@ssf@@UAGJABU_GUID@@PAPAX@Z ENDP ; ssf::CRenderer::NonDelegatingQueryInterface
_TEXT	ENDS
PUBLIC	??0CRenderer@ssf@@QAE@PAVCCritSec@@@Z		; ssf::CRenderer::CRenderer
; Function compile flags: /Ogtp
;	COMDAT ??0CRenderer@ssf@@QAE@PAVCCritSec@@@Z
_TEXT	SEGMENT
_pLock$ = 8						; size = 4
??0CRenderer@ssf@@QAE@PAVCCritSec@@@Z PROC		; ssf::CRenderer::CRenderer, COMDAT
; _this$ = esi

; 35   : 	{

	push	ebp
	mov	ebp, esp
	push	OFFSET ?m_cObjects@CBaseObject@@0JA	; CBaseObject::m_cObjects
	call	DWORD PTR __imp__InterlockedIncrement@4
	mov	eax, DWORD PTR _pLock$[ebp]
	mov	DWORD PTR [esi+4], esi
	mov	DWORD PTR [esi+8], 0
	mov	DWORD PTR [esi+12], OFFSET ??_7ISubPicProviderEx@@6B@
	mov	DWORD PTR [esi+16], eax
	mov	DWORD PTR [esi+20], OFFSET ??_7ISubStream@@6B@
	mov	DWORD PTR [esi], OFFSET ??_7CRenderer@ssf@@6BCUnknown@@@
	mov	DWORD PTR [esi+12], OFFSET ??_7CRenderer@ssf@@6BISubPicProviderEx@@@
	mov	DWORD PTR [esi+20], OFFSET ??_7CRenderer@ssf@@6B@
	call	?AfxGetStringManager@@YGPAUIAtlStringMgr@ATL@@XZ ; AfxGetStringManager
	test	eax, eax
	jne	SHORT $LN33@CRenderer@2
	push	-2147467259				; 80004005H
	call	?AtlThrowImpl@ATL@@YGXJ@Z		; ATL::AtlThrowImpl
$LN69@CRenderer@2:
$LN33@CRenderer@2:
	mov	edx, DWORD PTR [eax]
	mov	ecx, eax
	mov	eax, DWORD PTR [edx+12]
	call	eax
	add	eax, 16					; 00000010H
	mov	DWORD PTR [esi+24], eax
	call	?AfxGetStringManager@@YGPAUIAtlStringMgr@ATL@@XZ ; AfxGetStringManager
	test	eax, eax
	jne	SHORT $LN55@CRenderer@2
	push	-2147467259				; 80004005H
	call	?AtlThrowImpl@ATL@@YGXJ@Z		; ATL::AtlThrowImpl
$LN70@CRenderer@2:
$LN55@CRenderer@2:
	mov	edx, DWORD PTR [eax]
	mov	ecx, eax
	mov	eax, DWORD PTR [edx+12]
	call	eax
	add	eax, 16					; 00000010H
	mov	DWORD PTR [esi+28], eax
	mov	DWORD PTR [esi+32], 0
	mov	DWORD PTR [esi+36], 0

; 36   : 	}

	mov	eax, esi
	pop	ebp
	ret	4
$LN68@CRenderer@2:
??0CRenderer@ssf@@QAE@PAVCCritSec@@@Z ENDP		; ssf::CRenderer::CRenderer
; Function compile flags: /Ogtp
;	COMDAT ?GetStreamInfo@CRenderer@ssf@@UAGJHPAPA_WPAK@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_iStream$ = 12						; size = 4
_ppName$ = 16						; size = 4
_pLCID$ = 20						; size = 4
?GetStreamInfo@CRenderer@ssf@@UAGJHPAPA_WPAK@Z PROC	; ssf::CRenderer::GetStreamInfo, COMDAT

; 203  : 	{

	push	ebp
	mov	ebp, esp

; 204  : 		if(iStream != 0) return E_INVALIDARG;

	cmp	DWORD PTR _iStream$[ebp], 0
	je	SHORT $LN4@GetStreamI
	mov	eax, -2147024809			; 80070057H

; 220  : 	}

	pop	ebp
	ret	16					; 00000010H
$LN4@GetStreamI:
	push	esi

; 205  : 
; 206  : 		if(ppName)

	mov	esi, DWORD PTR _ppName$[ebp]
	push	edi
	test	esi, esi
	je	SHORT $LN32@GetStreamI

; 207  : 		{
; 208  : 			if(!(*ppName = (WCHAR*)CoTaskMemAlloc((m_name.GetLength()+1)*sizeof(WCHAR))))

	mov	edi, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edi+8]
	mov	eax, DWORD PTR [eax-12]
	lea	ecx, DWORD PTR [eax+eax+2]
	push	ecx
	call	DWORD PTR __imp__CoTaskMemAlloc@4
	mov	DWORD PTR [esi], eax
	test	eax, eax
	jne	SHORT $LN2@GetStreamI

; 209  : 				return E_OUTOFMEMORY;

	pop	edi
	mov	eax, -2147024882			; 8007000eH
	pop	esi

; 220  : 	}

	pop	ebp
	ret	16					; 00000010H
$LN2@GetStreamI:

; 210  : 
; 211  : 			wcscpy(*ppName, CStringW(m_name));

	mov	eax, DWORD PTR [edi+8]
	sub	eax, 16					; 00000010H
	push	eax
	call	?CloneData@?$CSimpleStringT@_W$0A@@ATL@@CAPAUCStringData@2@PAU32@@Z ; ATL::CSimpleStringT<wchar_t,0>::CloneData
	mov	esi, DWORD PTR [esi]
	add	esp, 4
	lea	edx, DWORD PTR [eax+16]
$LL7@GetStreamI:
	movzx	ecx, WORD PTR [edx]
	mov	WORD PTR [esi], cx
	add	edx, 2
	add	esi, 2
	test	cx, cx
	jne	SHORT $LL7@GetStreamI
	lea	edx, DWORD PTR [eax+12]
	or	ecx, -1
	lock	 xadd	 DWORD PTR [edx], ecx
	dec	ecx
	test	ecx, ecx
	jg	SHORT $LN32@GetStreamI
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	push	eax
	mov	eax, DWORD PTR [edx+4]
	call	eax
$LN32@GetStreamI:

; 212  : 		}
; 213  : 
; 214  : 		if(pLCID)

	mov	eax, DWORD PTR _pLCID$[ebp]
	test	eax, eax
	je	SHORT $LN1@GetStreamI

; 215  : 		{
; 216  : 			*pLCID = 0; // TODO

	mov	DWORD PTR [eax], 0
$LN1@GetStreamI:
	pop	edi

; 217  : 		}
; 218  : 
; 219  : 		return S_OK;

	xor	eax, eax
	pop	esi

; 220  : 	}

	pop	ebp
	ret	16					; 00000010H
?GetStreamInfo@CRenderer@ssf@@UAGJHPAPA_WPAK@Z ENDP	; ssf::CRenderer::GetStreamInfo
PUBLIC	?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z ; ssf::CRenderer::Open
;	COMDAT xdata$x
; File d:\program files (x86)\microsoft visual studio 10.0\vc\atlmfc\include\atlsimpstr.h
xdata$x	SEGMENT
__unwindtable$?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z$2
	DD	00H
	DD	00H
	DD	00H
	DD	00H
__catchsym$?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z$5 DD 08H
	DD	FLAT:??_R0?AVException@ssf@@@8
	DD	0ffffffecH
	DD	FLAT:__catch$?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z$0
__tryblocktable$?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z DD 01H
	DD	01H
	DD	02H
	DD	01H
	DD	FLAT:__catchsym$?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z$5
__ehfuncinfo$?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z DD 019930522H
	DD	03H
	DD	FLAT:__unwindtable$?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z
	DD	01H
	DD	FLAT:__tryblocktable$?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z
	DD	2 DUP(00H)
	DD	00H
	DD	01H
; Function compile flags: /Ogtp
; File e:\github\codesandnotes\xy-vsfilter\src\subtitles\ssf.cpp
xdata$x	ENDS
;	COMDAT ?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z
_TEXT	SEGMENT
__$EHRec$ = -16						; size = 16
tv257 = 8						; size = 4
_this$ = 8						; size = 4
_s$ = 12						; size = 4
_name$ = 16						; size = 4
?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z PROC ; ssf::CRenderer::Open, COMDAT

; 75   : 	{

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	mov	DWORD PTR fs:0, esp
	sub	esp, 12					; 0000000cH
	push	ebx
	mov	ebx, DWORD PTR _this$[ebp]
	push	esi
	push	edi
	mov	DWORD PTR __$EHRec$[ebp], esp
	xor	edi, edi

; 76   : 		m_fn.Empty();

	lea	ecx, DWORD PTR [ebx+24]
	mov	DWORD PTR __$EHRec$[ebp+12], edi
	call	?Empty@?$CSimpleStringT@_W$0A@@ATL@@QAEXXZ ; ATL::CSimpleStringT<wchar_t,0>::Empty

; 77   : 		m_name.Empty();

	lea	ecx, DWORD PTR [ebx+28]
	mov	DWORD PTR tv257[ebp], ecx
	call	?Empty@?$CSimpleStringT@_W$0A@@ATL@@QAEXXZ ; ATL::CSimpleStringT<wchar_t,0>::Empty

; 78   : 		m_file.Free();

	mov	ecx, DWORD PTR [ebx+32]
	cmp	ecx, edi
	je	SHORT $LN17@Open
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	push	1
	call	edx
$LN17@Open:
	mov	DWORD PTR [ebx+32], edi

; 79   : 		m_renderer.Free();

	mov	ecx, DWORD PTR [ebx+36]
	cmp	ecx, edi
	je	SHORT $LN21@Open
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	push	1
	call	edx
$LN21@Open:

; 80   : 
; 81   : 		try
; 82   : 		{
; 83   : 			m_file.Attach(new SubtitleFile());

	push	136					; 00000088H
	mov	DWORD PTR [ebx+36], edi
	mov	BYTE PTR __$EHRec$[ebp+12], 1
	call	??2@YAPAXI@Z				; operator new
	mov	esi, eax
	add	esp, 4
	cmp	esi, edi
	je	SHORT $LN4@Open
	call	??0NodeFactory@ssf@@QAE@XZ		; ssf::NodeFactory::NodeFactory
	mov	DWORD PTR [esi], OFFSET ??_7SubtitleFile@ssf@@6B@
	mov	DWORD PTR [esi+96], edi
	mov	DWORD PTR [esi+100], edi
	mov	DWORD PTR [esi+104], edi
	mov	DWORD PTR [esi+108], edi
	mov	DWORD PTR [esi+112], edi
	mov	DWORD PTR [esi+116], 10			; 0000000aH
	mov	DWORD PTR [esi+120], edi
	mov	DWORD PTR [esi+124], edi
	mov	DWORD PTR [esi+128], edi
	mov	DWORD PTR [esi+132], edi
	jmp	SHORT $LN5@Open
$LN4@Open:
	xor	esi, esi
$LN5@Open:

; 84   : 			m_file->Parse(s);

	mov	eax, DWORD PTR _s$[ebp]
	push	eax
	push	esi
	mov	DWORD PTR [ebx+32], esi
	call	?Parse@SubtitleFile@ssf@@QAEXAAVInputStream@2@@Z ; ssf::SubtitleFile::Parse

; 85   : 			m_renderer.Attach(new Renderer());

	push	320					; 00000140H
	call	??2@YAPAXI@Z				; operator new
	add	esp, 4
	cmp	eax, edi
	je	SHORT $LN6@Open
	mov	edi, eax
	call	??0Renderer@ssf@@QAE@XZ			; ssf::Renderer::Renderer
	jmp	SHORT $LN7@Open
$LN6@Open:
	xor	eax, eax
$LN7@Open:

; 86   : 			m_name = name;

	lea	ecx, DWORD PTR _name$[ebp]
	push	ecx
	mov	ecx, DWORD PTR tv257[ebp]
	mov	DWORD PTR [ebx+36], eax
	call	??4?$CSimpleStringT@_W$0A@@ATL@@QAEAAV01@ABV01@@Z ; ATL::CSimpleStringT<wchar_t,0>::operator=

; 87   : 			return true;

	mov	DWORD PTR __$EHRec$[ebp+12], -1
	mov	eax, DWORD PTR _name$[ebp]
	add	eax, -16				; fffffff0H
	lea	edx, DWORD PTR [eax+12]
	or	ecx, -1
	lock	 xadd	 DWORD PTR [edx], ecx
	dec	ecx
	test	ecx, ecx
	jg	SHORT $LN65@Open
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	push	eax
	mov	eax, DWORD PTR [edx+4]
	call	eax
$LN65@Open:
	mov	al, 1

; 95   : 	}

	mov	ecx, DWORD PTR __$EHRec$[ebp+4]
	mov	DWORD PTR fs:0, ecx
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
__catch$?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z$0:

; 88   : 		}
; 89   : 		catch(Exception& e)
; 90   : 		{
; 91   : 			TRACE(_T("%s\n"), e.ToString());
; 92   : 		}

	mov	eax, $LN14@Open
	ret	0
$LN14@Open:

; 93   : 
; 94   : 		return false;

	lea	ecx, DWORD PTR _name$[ebp]
	call	??1?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ ; ATL::CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >::~CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >

; 95   : 	}

	mov	ecx, DWORD PTR __$EHRec$[ebp+4]
	pop	edi
	pop	esi
	xor	al, al
	mov	DWORD PTR fs:0, ecx
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z$2:
	lea	ecx, DWORD PTR _name$[ebp]
	jmp	??1?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ ; ATL::CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >::~CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >
__ehhandler$?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z:
	mov	eax, OFFSET __ehfuncinfo$?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z ENDP ; ssf::CRenderer::Open
PUBLIC	?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z ; ssf::CRenderer::Open
;	COMDAT xdata$x
; File d:\program files (x86)\microsoft visual studio 10.0\vc\atlmfc\include\atlsimpstr.h
xdata$x	SEGMENT
__unwindtable$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$2
	DD	00H
	DD	FLAT:__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$3
	DD	01H
	DD	FLAT:__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$4
	DD	02H
	DD	FLAT:__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$5
	DD	02H
	DD	FLAT:__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$6
	DD	02H
	DD	FLAT:__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$7
	DD	01H
	DD	00H
	DD	06H
	DD	FLAT:__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$8
	DD	07H
	DD	FLAT:__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$12
	DD	07H
	DD	FLAT:__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$9
	DD	06H
	DD	FLAT:__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$9
	DD	01H
	DD	00H
__catchsym$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$13 DD 08H
	DD	FLAT:??_R0?AVException@ssf@@@8
	DD	0ffffffb4H
	DD	FLAT:__catch$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$0
__tryblocktable$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z DD 06H
	DD	0aH
	DD	0bH
	DD	01H
	DD	FLAT:__catchsym$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$13
__ehfuncinfo$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z DD 019930522H
	DD	0cH
	DD	FLAT:__unwindtable$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z
	DD	01H
	DD	FLAT:__tryblocktable$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z
	DD	2 DUP(00H)
	DD	00H
	DD	01H
; Function compile flags: /Ogtp
; File e:\github\codesandnotes\xy-vsfilter\src\subtitles\ssf.cpp
xdata$x	ENDS
;	COMDAT ?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z
_TEXT	SEGMENT
$T820467 = -72						; size = 44
tv608 = -28						; size = 4
$T820466 = -24						; size = 4
$T820464 = -24						; size = 4
$T820463 = -24						; size = 4
$T820462 = -24						; size = 4
_str$315574 = -20					; size = 4
__$EHRec$ = -16						; size = 16
_this$ = 8						; size = 4
tv212 = 11						; size = 1
_fn$ = 12						; size = 4
_name$ = 16						; size = 4
?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z PROC ; ssf::CRenderer::Open, COMDAT

; 43   : 	{

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	mov	DWORD PTR fs:0, esp
	sub	esp, 68					; 00000044H
	push	ebx
	push	esi
	push	edi
	mov	DWORD PTR __$EHRec$[ebp], esp

; 44   : 		m_fn.Empty();

	mov	esi, DWORD PTR _this$[ebp]
	lea	ecx, DWORD PTR [esi+24]
	mov	DWORD PTR __$EHRec$[ebp+12], 1
	mov	DWORD PTR tv608[ebp], ecx
	call	?Empty@?$CSimpleStringT@_W$0A@@ATL@@QAEXXZ ; ATL::CSimpleStringT<wchar_t,0>::Empty

; 45   : 		m_name.Empty();

	lea	ecx, DWORD PTR [esi+28]
	call	?Empty@?$CSimpleStringT@_W$0A@@ATL@@QAEXXZ ; ATL::CSimpleStringT<wchar_t,0>::Empty

; 46   : 		m_file.Free();

	mov	ecx, DWORD PTR [esi+32]
	xor	ebx, ebx
	cmp	ecx, ebx
	je	SHORT $LN20@Open@2
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	push	1
	call	edx
$LN20@Open@2:
	mov	DWORD PTR [esi+32], ebx

; 47   : 		m_renderer.Free();

	mov	ecx, DWORD PTR [esi+36]
	cmp	ecx, ebx
	je	SHORT $LN24@Open@2
	mov	eax, DWORD PTR [ecx]
	mov	edx, DWORD PTR [eax]
	push	1
	call	edx
$LN24@Open@2:

; 48   : 
; 49   : 		if(name.IsEmpty())

	mov	eax, DWORD PTR _name$[ebp]
	mov	DWORD PTR [esi+36], ebx
	cmp	DWORD PTR [eax-12], ebx
	jne	$LN112@Open@2

; 50   : 		{
; 51   : 			CString str = fn;

	mov	eax, DWORD PTR _fn$[ebp]
	add	eax, -16				; fffffff0H
	push	eax
	call	?CloneData@?$CSimpleStringT@_W$0A@@ATL@@CAPAUCStringData@2@PAU32@@Z ; ATL::CSimpleStringT<wchar_t,0>::CloneData
	add	eax, 16					; 00000010H
	add	esp, 4
	mov	DWORD PTR _str$315574[ebp], eax

; 52   : 			str.Replace('\\', '/');

	push	47					; 0000002fH
	push	92					; 0000005cH
	lea	ecx, DWORD PTR _str$315574[ebp]
	push	ecx
	mov	BYTE PTR __$EHRec$[ebp+12], 2
	call	?Replace@?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAEH_W0@Z ; ATL::CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >::Replace

; 53   : 			name = str.Left(str.ReverseFind('.'));

	mov	esi, DWORD PTR _str$315574[ebp]
	push	46					; 0000002eH
	push	esi
	call	_wcsrchr
	add	esp, 8
	cmp	eax, ebx
	jne	SHORT $LN45@Open@2
	or	eax, -1
	jmp	SHORT $LN46@Open@2
$LN45@Open@2:
	sub	eax, esi
	sar	eax, 1
$LN46@Open@2:
	push	eax
	lea	edx, DWORD PTR $T820462[ebp]
	push	edx
	lea	ecx, DWORD PTR _str$315574[ebp]
	call	?Left@?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QBE?AV12@H@Z ; ATL::CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >::Left
	push	eax
	lea	ecx, DWORD PTR _name$[ebp]
	mov	BYTE PTR __$EHRec$[ebp+12], 3
	call	??4?$CSimpleStringT@_W$0A@@ATL@@QAEAAV01@ABV01@@Z ; ATL::CSimpleStringT<wchar_t,0>::operator=
	mov	BYTE PTR __$EHRec$[ebp+12], 2
	mov	eax, DWORD PTR $T820462[ebp]
	add	eax, -16				; fffffff0H
	lea	ecx, DWORD PTR [eax+12]
	or	edx, -1
	lock	 xadd	 DWORD PTR [ecx], edx
	dec	edx
	test	edx, edx
	jg	SHORT $LN61@Open@2
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	push	eax
	mov	eax, DWORD PTR [edx+4]
	call	eax
$LN61@Open@2:

; 54   : 			name = name.Mid(name.ReverseFind('/')+1);

	mov	ecx, DWORD PTR _name$[ebp]
	push	47					; 0000002fH
	push	ecx
	call	_wcsrchr
	add	esp, 8
	cmp	eax, ebx
	jne	SHORT $LN66@Open@2
	or	eax, -1
	jmp	SHORT $LN67@Open@2
$LN66@Open@2:
	sub	eax, DWORD PTR _name$[ebp]
	sar	eax, 1
$LN67@Open@2:
	inc	eax
	push	eax
	lea	edx, DWORD PTR $T820463[ebp]
	push	edx
	lea	ecx, DWORD PTR _name$[ebp]
	call	?Mid@?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QBE?AV12@H@Z ; ATL::CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >::Mid
	push	eax
	lea	ecx, DWORD PTR _name$[ebp]
	mov	BYTE PTR __$EHRec$[ebp+12], 4
	call	??4?$CSimpleStringT@_W$0A@@ATL@@QAEAAV01@ABV01@@Z ; ATL::CSimpleStringT<wchar_t,0>::operator=
	mov	BYTE PTR __$EHRec$[ebp+12], 2
	mov	eax, DWORD PTR $T820463[ebp]
	add	eax, -16				; fffffff0H
	lea	ecx, DWORD PTR [eax+12]
	or	edx, -1
	lock	 xadd	 DWORD PTR [ecx], edx
	dec	edx
	test	edx, edx
	jg	SHORT $LN82@Open@2
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	push	eax
	mov	eax, DWORD PTR [edx+4]
	call	eax
$LN82@Open@2:

; 55   : 			name = name.Mid(name.ReverseFind('.')+1);

	mov	ecx, DWORD PTR _name$[ebp]
	push	46					; 0000002eH
	push	ecx
	call	_wcsrchr
	add	esp, 8
	cmp	eax, ebx
	jne	SHORT $LN87@Open@2
	or	eax, -1
	jmp	SHORT $LN88@Open@2
$LN87@Open@2:
	sub	eax, DWORD PTR _name$[ebp]
	sar	eax, 1
$LN88@Open@2:
	inc	eax
	push	eax
	lea	edx, DWORD PTR $T820464[ebp]
	push	edx
	lea	ecx, DWORD PTR _name$[ebp]
	call	?Mid@?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QBE?AV12@H@Z ; ATL::CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >::Mid
	push	eax
	lea	ecx, DWORD PTR _name$[ebp]
	mov	BYTE PTR __$EHRec$[ebp+12], 5
	call	??4?$CSimpleStringT@_W$0A@@ATL@@QAEAAV01@ABV01@@Z ; ATL::CSimpleStringT<wchar_t,0>::operator=
	mov	BYTE PTR __$EHRec$[ebp+12], 2
	mov	eax, DWORD PTR $T820464[ebp]
	add	eax, -16				; fffffff0H
	lea	ecx, DWORD PTR [eax+12]
	or	edx, -1
	lock	 xadd	 DWORD PTR [ecx], edx
	dec	edx
	test	edx, edx
	jg	SHORT $LN103@Open@2
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	push	eax
	mov	eax, DWORD PTR [edx+4]
	call	eax
$LN103@Open@2:

; 56   : 		}

	lea	eax, DWORD PTR [esi-16]
	mov	BYTE PTR __$EHRec$[ebp+12], 1
	lea	ecx, DWORD PTR [eax+12]
	or	edx, -1
	lock	 xadd	 DWORD PTR [ecx], edx
	dec	edx
	test	edx, edx
	jg	SHORT $LN112@Open@2
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	push	eax
	mov	eax, DWORD PTR [edx+4]
	call	eax
$LN112@Open@2:

; 57   : 
; 58   : 		try
; 59   : 		{

	mov	BYTE PTR __$EHRec$[ebp+12], 6

; 60   : 			if(Open(FileInputStream(fn), name)) 

	mov	eax, DWORD PTR _name$[ebp]
	push	ecx
	add	eax, -16				; fffffff0H
	mov	DWORD PTR $T820466[ebp], esp
	mov	esi, esp
	push	eax
	call	?CloneData@?$CSimpleStringT@_W$0A@@ATL@@CAPAUCStringData@2@PAU32@@Z ; ATL::CSimpleStringT<wchar_t,0>::CloneData
	add	eax, 16					; 00000010H
	add	esp, 4
	mov	DWORD PTR [esi], eax
	mov	eax, DWORD PTR _fn$[ebp]
	mov	esi, eax
	mov	DWORD PTR $T820467[ebp+4], ebx
	mov	DWORD PTR $T820467[ebp+8], -1
	mov	DWORD PTR $T820467[ebp+12], ebx
	mov	DWORD PTR $T820467[ebp+16], ebx
	mov	DWORD PTR $T820467[ebp+20], ebx
	mov	DWORD PTR $T820467[ebp+24], ebx
	mov	DWORD PTR $T820467[ebp+28], ebx
	mov	DWORD PTR $T820467[ebp+32], ebx
	mov	DWORD PTR $T820467[ebp+36], 10		; 0000000aH
	push	OFFSET ??_C@_13BPINEIPE@?$AAr?$AA?$AA@
	push	eax
	lea	ecx, DWORD PTR $T820467[ebp+40]
	mov	BYTE PTR __$EHRec$[ebp+12], 8
	mov	edi, OFFSET ??_7FileInputStream@ssf@@6B@
	push	ecx
	mov	DWORD PTR $T820467[ebp], edi
	mov	DWORD PTR $T820467[ebp+40], ebx
	call	__wfopen_s
	add	esp, 12					; 0000000cH
	test	eax, eax
	je	SHORT $LN128@Open@2
	push	esi
	push	OFFSET ??_C@_1CM@BJCCGLHN@?$AAc?$AAa?$AAn?$AAn?$AAo?$AAt?$AA?5?$AAo?$AAp?$AAe?$AAn?$AA?5?$AAf?$AAi?$AAl?$AAe?$AA?5?$AA?8?$AA?$CF?$AAs?$AA?8?$AA?$AA@
	lea	edx, DWORD PTR $T820467[ebp]
	push	edx
	call	?ThrowError@Stream@ssf@@QAAXPB_WZZ	; ssf::Stream::ThrowError
$LN199@Open@2:
$LN128@Open@2:
	mov	BYTE PTR __$EHRec$[ebp+12], 9
	mov	ecx, DWORD PTR _this$[ebp]
	lea	eax, DWORD PTR $T820467[ebp]
	push	eax
	push	ecx
	mov	BYTE PTR __$EHRec$[ebp+12], 10		; 0000000aH
	call	?Open@CRenderer@ssf@@QAE_NAAVInputStream@2@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z ; ssf::CRenderer::Open
	mov	BYTE PTR __$EHRec$[ebp+12], 6
	mov	BYTE PTR tv212[ebp], al
	mov	eax, DWORD PTR $T820467[ebp+40]
	mov	DWORD PTR $T820467[ebp], edi
	cmp	eax, ebx
	je	SHORT $LN139@Open@2
	push	eax
	call	_fclose
	add	esp, 4
	mov	DWORD PTR $T820467[ebp+40], ebx
$LN139@Open@2:
	lea	esi, DWORD PTR $T820467[ebp+16]
	mov	DWORD PTR $T820467[ebp], OFFSET ??_7InputStream@ssf@@6B@
	call	?RemoveAll@?$CAtlList@HV?$CElementTraits@H@ATL@@@ATL@@QAEXXZ ; ATL::CAtlList<int,ATL::CElementTraits<int> >::RemoveAll
	cmp	BYTE PTR tv212[ebp], bl
	je	SHORT $LN1@Open@2

; 61   : 			{
; 62   : 				m_fn = fn;

	mov	ecx, DWORD PTR tv608[ebp]
	lea	edx, DWORD PTR _fn$[ebp]
	push	edx
	call	??4?$CSimpleStringT@_W$0A@@ATL@@QAEAAV01@ABV01@@Z ; ATL::CSimpleStringT<wchar_t,0>::operator=

; 63   : 				return true;

	mov	BYTE PTR __$EHRec$[ebp+12], bl
	mov	eax, DWORD PTR _fn$[ebp]
	add	eax, -16				; fffffff0H
	lea	ecx, DWORD PTR [eax+12]
	or	edx, -1
	lock	 xadd	 DWORD PTR [ecx], edx
	dec	edx
	test	edx, edx
	jg	SHORT $LN162@Open@2
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	push	eax
	mov	eax, DWORD PTR [edx+4]
	call	eax
$LN162@Open@2:
	mov	DWORD PTR __$EHRec$[ebp+12], -1
	mov	eax, DWORD PTR _name$[ebp]
	add	eax, -16				; fffffff0H
	lea	ecx, DWORD PTR [eax+12]
	or	edx, -1
	lock	 xadd	 DWORD PTR [ecx], edx
	dec	edx
	test	edx, edx
	jg	SHORT $LN171@Open@2
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	push	eax
	mov	eax, DWORD PTR [edx+4]
	call	eax
$LN171@Open@2:
	mov	al, 1

; 72   : 	}

	mov	ecx, DWORD PTR __$EHRec$[ebp+4]
	mov	DWORD PTR fs:0, ecx
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN1@Open@2:
	mov	DWORD PTR __$EHRec$[ebp+12], 1
	jmp	SHORT $LN17@Open@2
__catch$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$0:

; 64   : 			}
; 65   : 		}
; 66   : 		catch(Exception& e)
; 67   : 		{
; 68   : 			TRACE(_T("%s\n"), e.ToString());
; 69   : 		}

	mov	DWORD PTR __$EHRec$[ebp+12], 1
	mov	eax, $LN196@Open@2
	ret	0
$LN196@Open@2:
	xor	ebx, ebx
$LN17@Open@2:

; 70   : 
; 71   : 		return false;	

	mov	BYTE PTR __$EHRec$[ebp+12], bl
	mov	eax, DWORD PTR _fn$[ebp]
	add	eax, -16				; fffffff0H
	lea	ecx, DWORD PTR [eax+12]
	or	edx, -1
	lock	 xadd	 DWORD PTR [ecx], edx
	dec	edx
	test	edx, edx
	jg	SHORT $LN180@Open@2
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	push	eax
	mov	eax, DWORD PTR [edx+4]
	call	eax
$LN180@Open@2:
	mov	DWORD PTR __$EHRec$[ebp+12], -1
	mov	eax, DWORD PTR _name$[ebp]
	add	eax, -16				; fffffff0H
	lea	ecx, DWORD PTR [eax+12]
	or	edx, -1
	lock	 xadd	 DWORD PTR [ecx], edx
	dec	edx
	test	edx, edx
	jg	SHORT $LN189@Open@2
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	push	eax
	mov	eax, DWORD PTR [edx+4]
	call	eax
$LN189@Open@2:

; 72   : 	}

	mov	ecx, DWORD PTR __$EHRec$[ebp+4]
	pop	edi
	pop	esi
	xor	al, al
	mov	DWORD PTR fs:0, ecx
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN198@Open@2:
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$2:
	lea	ecx, DWORD PTR _name$[ebp]
	jmp	??1?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ ; ATL::CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >::~CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >
__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$3:
	lea	ecx, DWORD PTR _fn$[ebp]
	jmp	??1?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ ; ATL::CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >::~CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >
__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$4:
	lea	ecx, DWORD PTR _str$315574[ebp]
	jmp	??1?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ ; ATL::CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >::~CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >
__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$5:
	lea	ecx, DWORD PTR $T820462[ebp]
	jmp	??1?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ ; ATL::CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >::~CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >
__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$6:
	lea	ecx, DWORD PTR $T820463[ebp]
	jmp	??1?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ ; ATL::CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >::~CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >
__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$7:
	lea	ecx, DWORD PTR $T820464[ebp]
	jmp	??1?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ ; ATL::CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >::~CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >
__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$8:
	mov	ecx, DWORD PTR $T820466[ebp]
	jmp	??1?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ ; ATL::CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >::~CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >
__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$12:
	lea	edi, DWORD PTR $T820467[ebp]
	jmp	??1InputStream@ssf@@UAE@XZ		; ssf::InputStream::~InputStream
__unwindfunclet$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z$9:
	lea	edi, DWORD PTR $T820467[ebp]
	jmp	??1FileInputStream@ssf@@UAE@XZ		; ssf::FileInputStream::~FileInputStream
__ehhandler$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z:
	mov	eax, OFFSET __ehfuncinfo$?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z ENDP ; ssf::CRenderer::Open
;	COMDAT xdata$x
; File e:\github\codesandnotes\xy-vsfilter\src\filters\baseclasses\wxutil.h
xdata$x	SEGMENT
__unwindtable$?Reload@CRenderer@ssf@@UAGJXZ DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?Reload@CRenderer@ssf@@UAGJXZ$0
	DD	00H
	DD	FLAT:__unwindfunclet$?Reload@CRenderer@ssf@@UAGJXZ$1
__ehfuncinfo$?Reload@CRenderer@ssf@@UAGJXZ DD 019930522H
	DD	02H
	DD	FLAT:__unwindtable$?Reload@CRenderer@ssf@@UAGJXZ
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
; Function compile flags: /Ogtp
; File e:\github\codesandnotes\xy-vsfilter\src\subtitles\ssf.cpp
xdata$x	ENDS
;	COMDAT ?Reload@CRenderer@ssf@@UAGJXZ
_TEXT	SEGMENT
$T842750 = -20						; size = 4
$T842749 = -16						; size = 4
__$EHRec$ = -12						; size = 12
_csAutoLock$ = 8					; size = 4
_this$ = 8						; size = 4
?Reload@CRenderer@ssf@@UAGJXZ PROC			; ssf::CRenderer::Reload, COMDAT

; 233  : 	{

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?Reload@CRenderer@ssf@@UAGJXZ
	mov	eax, DWORD PTR fs:0
	push	eax
	mov	DWORD PTR fs:0, esp
	sub	esp, 8
	push	ebx
	push	esi

; 234  : 		CAutoLock csAutoLock(m_pLock);

	mov	esi, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [esi-4]
	push	edi
	push	eax
	mov	DWORD PTR _csAutoLock$[ebp], eax
	call	DWORD PTR __imp__EnterCriticalSection@4
	xor	ebx, ebx
	mov	DWORD PTR __$EHRec$[ebp+8], ebx

; 235  : 
; 236  : 		return !m_fn.IsEmpty() && Open(m_fn, m_name) ? S_OK : E_FAIL;

	mov	eax, DWORD PTR [esi+4]
	cmp	DWORD PTR [eax-12], ebx
	je	SHORT $LN3@Reload
	mov	eax, DWORD PTR [esi+8]
	push	ecx
	sub	eax, 16					; 00000010H
	mov	DWORD PTR $T842749[ebp], esp
	mov	edi, esp
	push	eax
	call	?CloneData@?$CSimpleStringT@_W$0A@@ATL@@CAPAUCStringData@2@PAU32@@Z ; ATL::CSimpleStringT<wchar_t,0>::CloneData
	add	eax, 16					; 00000010H
	mov	DWORD PTR [edi], eax
	mov	BYTE PTR __$EHRec$[ebp+8], 1
	mov	eax, DWORD PTR [esi+4]
	sub	eax, 16					; 00000010H
	mov	DWORD PTR $T842750[ebp], esp
	mov	edi, esp
	push	eax
	call	?CloneData@?$CSimpleStringT@_W$0A@@ATL@@CAPAUCStringData@2@PAU32@@Z ; ATL::CSimpleStringT<wchar_t,0>::CloneData
	add	esp, 4
	add	eax, 16					; 00000010H
	add	esi, -20				; ffffffecH
	mov	DWORD PTR [edi], eax
	push	esi
	mov	BYTE PTR __$EHRec$[ebp+8], bl
	call	?Open@CRenderer@ssf@@QAE_NV?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@0@Z ; ssf::CRenderer::Open
	cmp	al, bl
	jne	SHORT $LN4@Reload
$LN3@Reload:
	mov	ebx, -2147467259			; 80004005H
$LN4@Reload:
	mov	ecx, DWORD PTR _csAutoLock$[ebp]
	push	ecx
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 237  : 	}

	mov	ecx, DWORD PTR __$EHRec$[ebp]
	pop	edi
	pop	esi
	mov	eax, ebx
	mov	DWORD PTR fs:0, ecx
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?Reload@CRenderer@ssf@@UAGJXZ$0:
	lea	eax, DWORD PTR _csAutoLock$[ebp]
	jmp	??1CAutoLock@@QAE@XZ			; CAutoLock::~CAutoLock
__unwindfunclet$?Reload@CRenderer@ssf@@UAGJXZ$1:
	mov	ecx, DWORD PTR $T842749[ebp]
	jmp	??1?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ ; ATL::CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >::~CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >
__ehhandler$?Reload@CRenderer@ssf@@UAGJXZ:
	mov	eax, OFFSET __ehfuncinfo$?Reload@CRenderer@ssf@@UAGJXZ
	jmp	___CxxFrameHandler3
text$x	ENDS
?Reload@CRenderer@ssf@@UAGJXZ ENDP			; ssf::CRenderer::Reload
PUBLIC	?Append@CRenderer@ssf@@QAEX_J0PB_W@Z		; ssf::CRenderer::Append
;	COMDAT xdata$x
; File e:\github\codesandnotes\xy-vsfilter\src\subtitles\libssf\stream.cpp
xdata$x	SEGMENT
__unwindtable$?Append@CRenderer@ssf@@QAEX_J0PB_W@Z DD 0ffffffffH
	DD	00H
	DD	00H
	DD	FLAT:__unwindfunclet$?Append@CRenderer@ssf@@QAEX_J0PB_W@Z$3
	DD	0ffffffffH
	DD	00H
__catchsym$?Append@CRenderer@ssf@@QAEX_J0PB_W@Z$4 DD 08H
	DD	FLAT:??_R0?AVException@ssf@@@8
	DD	0ffffffb8H
	DD	FLAT:__catch$?Append@CRenderer@ssf@@QAEX_J0PB_W@Z$0
__tryblocktable$?Append@CRenderer@ssf@@QAEX_J0PB_W@Z DD 00H
	DD	01H
	DD	02H
	DD	01H
	DD	FLAT:__catchsym$?Append@CRenderer@ssf@@QAEX_J0PB_W@Z$4
__ehfuncinfo$?Append@CRenderer@ssf@@QAEX_J0PB_W@Z DD 019930522H
	DD	03H
	DD	FLAT:__unwindtable$?Append@CRenderer@ssf@@QAEX_J0PB_W@Z
	DD	01H
	DD	FLAT:__tryblocktable$?Append@CRenderer@ssf@@QAEX_J0PB_W@Z
	DD	2 DUP(00H)
	DD	00H
	DD	01H
; Function compile flags: /Ogtp
; File e:\github\codesandnotes\xy-vsfilter\src\subtitles\ssf.cpp
xdata$x	ENDS
;	COMDAT ?Append@CRenderer@ssf@@QAEX_J0PB_W@Z
_TEXT	SEGMENT
$T842874 = -68						; size = 48
__$EHRec$ = -16						; size = 16
_rtStart$ = 8						; size = 8
_rtStop$ = 16						; size = 8
tv214 = 20						; size = 4
tv212 = 20						; size = 4
$T842875 = 20						; size = 4
_str$ = 24						; size = 4
?Append@CRenderer@ssf@@QAEX_J0PB_W@Z PROC		; ssf::CRenderer::Append, COMDAT
; _this$ = ecx

; 98   : 	{

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?Append@CRenderer@ssf@@QAEX_J0PB_W@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	mov	DWORD PTR fs:0, esp
	sub	esp, 60					; 0000003cH
	push	ebx
	push	esi
	mov	esi, ecx

; 99   : 		if(!m_file) return;

	xor	ebx, ebx
	push	edi
	mov	DWORD PTR __$EHRec$[ebp], esp
	cmp	DWORD PTR [esi+32], ebx
	je	$LN10@Append@6

; 100  : 
; 101  : 		try
; 102  : 		{
; 103  : 			m_file->Append(ssf::WCharInputStream(str), (float)rtStart / 10000000, (float)rtStop / 10000000);

	fild	QWORD PTR _rtStop$[ebp]
	mov	DWORD PTR __$EHRec$[ebp+12], ebx
	fld	QWORD PTR __real@416312d000000000
	push	ebx
	sub	esp, 12					; 0000000cH
	fdiv	ST(1), ST(0)
	mov	eax, DWORD PTR _str$[ebp]
	mov	ecx, esp
	fxch	ST(1)
	fstp	DWORD PTR tv214[ebp]
	fld	DWORD PTR tv214[ebp]
	fstp	DWORD PTR [esp+8]
	fild	QWORD PTR _rtStart$[ebp]
	fdivrp	ST(1), ST(0)
	fstp	DWORD PTR tv212[ebp]
	fld	DWORD PTR tv212[ebp]
	fstp	DWORD PTR [esp+4]
	mov	DWORD PTR $T842875[ebp], esp
	push	eax
	call	??0?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@PB_W@Z ; ATL::CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >::CStringT<wchar_t,StrTraitMFC<wchar_t,ATL::ChTraitsCRT<wchar_t> > >
	lea	ecx, DWORD PTR $T842874[ebp]
	push	ecx
	call	??0WCharInputStream@ssf@@QAE@V?$CStringT@_WV?$StrTraitMFC@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z ; ssf::WCharInputStream::WCharInputStream
	mov	BYTE PTR __$EHRec$[ebp+12], 1
	mov	ecx, DWORD PTR [esi+32]
	push	eax
	push	ecx
	call	?Append@SubtitleFile@ssf@@QAEXAAVInputStream@2@MM_N@Z ; ssf::SubtitleFile::Append
	mov	BYTE PTR __$EHRec$[ebp+12], bl
	mov	eax, DWORD PTR $T842874[ebp+40]
	add	eax, -16				; fffffff0H
	lea	edx, DWORD PTR [eax+12]
	or	ecx, -1
	lock	 xadd	 DWORD PTR [edx], ecx
	dec	ecx
	test	ecx, ecx
	jg	SHORT $LN29@Append@6
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx]
	push	eax
	mov	eax, DWORD PTR [edx+4]
	call	eax
$LN29@Append@6:
	lea	esi, DWORD PTR $T842874[ebp+16]
	mov	DWORD PTR $T842874[ebp], OFFSET ??_7InputStream@ssf@@6B@
	call	?RemoveAll@?$CAtlList@HV?$CElementTraits@H@ATL@@@ATL@@QAEXXZ ; ATL::CAtlList<int,ATL::CElementTraits<int> >::RemoveAll
$LN10@Append@6:

; 109  : 	}

	mov	ecx, DWORD PTR __$EHRec$[ebp+4]
	pop	edi
	pop	esi
	mov	DWORD PTR fs:0, ecx
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	20					; 00000014H
__catch$?Append@CRenderer@ssf@@QAEX_J0PB_W@Z$0:

; 104  : 		}
; 105  : 		catch(Exception& e)
; 106  : 		{
; 107  : 			TRACE(_T("%s\n"), e.ToString());
; 108  : 		}

	mov	eax, $LN10@Append@6
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?Append@CRenderer@ssf@@QAEX_J0PB_W@Z$3:
	lea	edi, DWORD PTR $T842874[ebp]
	jmp	??1WCharInputStream@ssf@@UAE@XZ
__ehhandler$?Append@CRenderer@ssf@@QAEX_J0PB_W@Z:
	mov	eax, OFFSET __ehfuncinfo$?Append@CRenderer@ssf@@QAEX_J0PB_W@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
?Append@CRenderer@ssf@@QAEX_J0PB_W@Z ENDP		; ssf::CRenderer::Append
;	COMDAT xdata$x
; File e:\github\codesandnotes\xy-vsfilter\src\filters\baseclasses\wxutil.h
xdata$x	SEGMENT
__unwindtable$?Render@CRenderer@ssf@@UAGJAAUSubPicDesc@@_JNAAUtagRECT@@@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?Render@CRenderer@ssf@@UAGJAAUSubPicDesc@@_JNAAUtagRECT@@@Z$0
	DD	00H
	DD	FLAT:__unwindfunclet$?Render@CRenderer@ssf@@UAGJAAUSubPicDesc@@_JNAAUtagRECT@@@Z$1
__ehfuncinfo$?Render@CRenderer@ssf@@UAGJAAUSubPicDesc@@_JNAAUtagRECT@@@Z DD 019930522H
	DD	02H
	DD	FLAT:__unwindtable$?Render@CRenderer@ssf@@UAGJAAUSubPicDesc@@_JNAAUtagRECT@@@Z
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
; Function compile flags: /Ogtp
; File e:\github\codesandnotes\xy-vsfilter\src\subtitles\ssf.cpp
xdata$x	ENDS
;	COMDAT ?Render@CRenderer@ssf@@UAGJAAUSubPicDesc@@_JNAAUtagRECT@@@Z
_TEXT	SEGMENT
tv460 = -108						; size = 4
$T873407 = -108						; size = 16
$T873404 = -108						; size = 8
_csAutoLock$ = -92					; size = 4
_bbox2$ = -88						; size = 16
$T873406 = -72						; size = 16
$T873403 = -72						; size = 16
$T873405 = -56						; size = 16
_subs$ = -40						; size = 24
__$EHRec$ = -12						; size = 12
_this$ = 8						; size = 4
_spd$ = 12						; size = 4
_rt$ = 16						; size = 8
_fps$ = 24						; size = 8
_bbox$ = 32						; size = 4
?Render@CRenderer@ssf@@UAGJAAUSubPicDesc@@_JNAAUtagRECT@@@Z PROC ; ssf::CRenderer::Render, COMDAT

; 159  : 	{

	push	ebp
	mov	ebp, esp
	and	esp, -8					; fffffff8H
	mov	eax, DWORD PTR fs:0
	push	-1
	push	__ehhandler$?Render@CRenderer@ssf@@UAGJAAUSubPicDesc@@_JNAAUtagRECT@@@Z
	push	eax
	mov	DWORD PTR fs:0, esp
	sub	esp, 96					; 00000060H
	push	ebx
	push	esi
	push	edi

; 160  : 		CheckPointer(m_file, E_UNEXPECTED);

	mov	edi, DWORD PTR _this$[ebp]
	xor	ebx, ebx
	cmp	DWORD PTR [edi+20], ebx
	jne	SHORT $LN6@Render@2
$LN99@Render@2:
	mov	eax, -2147418113			; 8000ffffH

; 186  : 	}

	mov	ecx, DWORD PTR __$EHRec$[esp+120]
	mov	DWORD PTR fs:0, ecx
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	28					; 0000001cH
$LN6@Render@2:

; 161  : 		CheckPointer(m_renderer, E_UNEXPECTED);	

	cmp	DWORD PTR [edi+24], ebx
	je	SHORT $LN99@Render@2

; 162  : 
; 163  : 		if(spd.type != MSP_RGB32) return E_INVALIDARG;

	mov	esi, DWORD PTR _spd$[ebp]
	cmp	DWORD PTR [esi], ebx
	je	SHORT $LN4@Render@2
	mov	eax, -2147024809			; 80070057H

; 186  : 	}

	mov	ecx, DWORD PTR __$EHRec$[esp+120]
	mov	DWORD PTR fs:0, ecx
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	28					; 0000001cH
$LN4@Render@2:

; 164  : 
; 165  : 		CAutoLock csAutoLock(m_pLock);

	mov	eax, DWORD PTR [edi+4]
	push	eax
	mov	DWORD PTR _csAutoLock$[esp+124], eax
	call	DWORD PTR __imp__EnterCriticalSection@4
	mov	DWORD PTR __$EHRec$[esp+128], ebx

; 166  : 
; 167  : 		CRect bbox2;
; 168  : 		bbox2.SetRectEmpty();

	lea	eax, DWORD PTR _bbox2$[esp+120]
	push	eax
	mov	DWORD PTR _bbox2$[esp+124], ebx
	mov	DWORD PTR _bbox2$[esp+128], ebx
	mov	DWORD PTR _bbox2$[esp+132], ebx
	mov	DWORD PTR _bbox2$[esp+136], ebx
	call	DWORD PTR __imp__SetRectEmpty@4

; 169  : 
; 170  : 		CAutoPtrList<Subtitle> subs;

	mov	DWORD PTR _subs$[esp+120], ebx
	mov	DWORD PTR _subs$[esp+124], ebx
	mov	DWORD PTR _subs$[esp+128], ebx
	mov	DWORD PTR _subs$[esp+132], ebx
	mov	DWORD PTR _subs$[esp+136], ebx
	mov	DWORD PTR _subs$[esp+140], 10		; 0000000aH

; 171  : 		m_file->Lookup((float)rt/10000000, subs);

	fild	QWORD PTR _rt$[ebp]
	mov	BYTE PTR __$EHRec$[esp+128], 1
	push	ecx
	fdiv	QWORD PTR __real@416312d000000000
	mov	ecx, DWORD PTR [edi+20]
	fstp	DWORD PTR tv460[esp+124]
	fld	DWORD PTR tv460[esp+124]
	fstp	DWORD PTR [esp]
	push	ecx
	lea	ecx, DWORD PTR _subs$[esp+128]
	call	?Lookup@SubtitleFile@ssf@@QAE_NMAAV?$CAutoPtrList@VSubtitle@ssf@@@ATL@@@Z ; ssf::SubtitleFile::Lookup

; 172  : 
; 173  : 		m_renderer->NextSegment(subs);

	mov	eax, DWORD PTR [edi+24]
	lea	edx, DWORD PTR _subs$[esp+120]
	push	edx
	push	eax
	call	?NextSegment@Renderer@ssf@@QAEXABV?$CAutoPtrList@VSubtitle@ssf@@@ATL@@@Z ; ssf::Renderer::NextSegment

; 174  : 
; 175  : 		POSITION pos = subs.GetHeadPosition();

	mov	edi, DWORD PTR _subs$[esp+120]

; 176  : 		while(pos)

	cmp	edi, ebx
	je	SHORT $LN2@Render@2
	npad	1
$LL3@Render@2:

; 177  : 		{
; 178  : 			const Subtitle* s = subs.GetNext(pos);

	cmp	edi, ebx
	je	$LN95@Render@2
	mov	ebx, DWORD PTR [edi+8]
	mov	edi, DWORD PTR [edi]

; 179  : 			const RenderedSubtitle* rs = m_renderer->Lookup(s, CSize(spd.w, spd.h), spd.vidrect);

	lea	ecx, DWORD PTR [esi+36]
	push	ecx
	lea	edx, DWORD PTR $T873403[esp+124]
	push	edx
	call	DWORD PTR __imp__CopyRect@8
	mov	ecx, DWORD PTR [esi+8]
	mov	eax, DWORD PTR [esi+4]
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR $T873404[esp+124], ecx
	lea	ecx, DWORD PTR $T873404[esp+120]
	push	ecx
	mov	DWORD PTR $T873404[esp+124], eax
	mov	eax, DWORD PTR [edx+24]
	push	ebx
	push	eax
	lea	ecx, DWORD PTR $T873403[esp+132]
	call	?Lookup@Renderer@ssf@@QAEPAVRenderedSubtitle@2@PBVSubtitle@2@ABVCSize@@ABVCRect@@@Z ; ssf::Renderer::Lookup

; 180  : 			if(rs) bbox2 |= rs->Draw(spd);

	test	eax, eax
	je	SHORT $LN72@Render@2
	push	esi
	lea	edx, DWORD PTR $T873405[esp+124]
	push	edx
	push	eax
	call	?Draw@RenderedSubtitle@ssf@@QBE?AVCRect@@AAUSubPicDesc@@@Z ; ssf::RenderedSubtitle::Draw
	push	eax
	lea	eax, DWORD PTR _bbox2$[esp+124]
	push	eax
	mov	ecx, eax
	push	ecx
	call	DWORD PTR __imp__UnionRect@12
$LN72@Render@2:

; 176  : 		while(pos)

	xor	ebx, ebx
	test	edi, edi
	jne	SHORT $LL3@Render@2
$LN2@Render@2:

; 181  : 		}
; 182  : 
; 183  : 		bbox = bbox2 & CRect(0, 0, spd.w, spd.h);

	mov	edx, DWORD PTR [esi+4]
	mov	eax, DWORD PTR [esi+8]
	lea	ecx, DWORD PTR $T873406[esp+120]
	mov	DWORD PTR $T873406[esp+128], edx
	push	ecx
	lea	edx, DWORD PTR _bbox2$[esp+124]
	mov	DWORD PTR $T873406[esp+136], eax
	push	edx
	lea	eax, DWORD PTR $T873407[esp+128]
	push	eax
	mov	DWORD PTR $T873406[esp+132], ebx
	mov	DWORD PTR $T873406[esp+136], ebx
	mov	DWORD PTR $T873407[esp+132], ebx
	mov	DWORD PTR $T873407[esp+136], ebx
	mov	DWORD PTR $T873407[esp+140], ebx
	mov	DWORD PTR $T873407[esp+144], ebx
	call	DWORD PTR __imp__IntersectRect@12
	mov	eax, DWORD PTR _bbox$[ebp]
	mov	ecx, DWORD PTR $T873407[esp+120]
	mov	edx, DWORD PTR $T873407[esp+124]
	mov	DWORD PTR [eax], ecx
	mov	ecx, DWORD PTR $T873407[esp+128]
	mov	DWORD PTR [eax+4], edx
	mov	edx, DWORD PTR $T873407[esp+132]
	mov	DWORD PTR [eax+8], ecx

; 184  : 
; 185  : 		return S_OK;

	lea	esi, DWORD PTR _subs$[esp+120]
	mov	DWORD PTR [eax+12], edx
	call	?RemoveAll@?$CAtlList@V?$CAutoPtr@VSubtitle@ssf@@@ATL@@V?$CAutoPtrElementTraits@VSubtitle@ssf@@@2@@ATL@@QAEXXZ ; ATL::CAtlList<ATL::CAutoPtr<ssf::Subtitle>,ATL::CAutoPtrElementTraits<ssf::Subtitle> >::RemoveAll
	mov	eax, DWORD PTR _csAutoLock$[esp+120]
	push	eax
	call	DWORD PTR __imp__LeaveCriticalSection@4

; 186  : 	}

	mov	ecx, DWORD PTR __$EHRec$[esp+120]
	pop	edi
	pop	esi
	xor	eax, eax
	mov	DWORD PTR fs:0, ecx
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	28					; 0000001cH
$LN95@Render@2:

; 177  : 		{
; 178  : 			const Subtitle* s = subs.GetNext(pos);

	push	-2147467259				; 80004005H
	call	?AtlThrowImpl@ATL@@YGXJ@Z		; ATL::AtlThrowImpl
$LN100@Render@2:
$LN98@Render@2:
	int	3
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?Render@CRenderer@ssf@@UAGJAAUSubPicDesc@@_JNAAUtagRECT@@@Z$0:
	lea	eax, DWORD PTR _csAutoLock$[ebp]
	jmp	??1CAutoLock@@QAE@XZ			; CAutoLock::~CAutoLock
__unwindfunclet$?Render@CRenderer@ssf@@UAGJAAUSubPicDesc@@_JNAAUtagRECT@@@Z$1:
	lea	esi, DWORD PTR _subs$[ebp]
	jmp	??1?$CAutoPtrList@VSubtitle@ssf@@@ATL@@QAE@XZ
__ehhandler$?Render@CRenderer@ssf@@UAGJAAUSubPicDesc@@_JNAAUtagRECT@@@Z:
	mov	eax, OFFSET __ehfuncinfo$?Render@CRenderer@ssf@@UAGJAAUSubPicDesc@@_JNAAUtagRECT@@@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
?Render@CRenderer@ssf@@UAGJAAUSubPicDesc@@_JNAAUtagRECT@@@Z ENDP ; ssf::CRenderer::Render
END
